import type { GmailMessage, JobberJob, PlaidTransaction, QuickBooksInvoice, ScenarioAnswerKey, ScenarioFixture } from "../scenarios/types";

const start = "2026-01-01";
const end = "2026-08-31";
const line = (id: string, amount: number) => ({ id, description: "Contract work", quantity: 1, unitPrice: amount, amount });
const invoice = (id: string, amount: number, balance = 0, projectId?: string, dueDate = "2026-08-15"): QuickBooksInvoice => ({ id, customerId: `customer-${id}`, invoiceNumber: id.toUpperCase(), projectId, issuedDate: "2026-07-01", dueDate, lines: [line(`line-${id}`, amount)], total: amount, balance });
const job = (id: string, amount: number, status: JobberJob["status"] = "completed", title = id): JobberJob => ({ id, clientId: `client-${id}`, jobNumber: id.toUpperCase(), title, status, completedAt: status === "completed" || status === "closed" ? "2026-07-01" : undefined, lineItems: [line(`job-line-${id}`, amount)], total: amount });
const tx = (id: string, amount: number, description: string, kind?: PlaidTransaction["kind"], date = "2026-08-15"): PlaidTransaction => ({ id, accountId: "bank-checking", date, amount, merchant: description, description, kind });
const mail = (id: string, subject: string, body = subject): GmailMessage => ({ id, threadId: `thread-${id}`, sender: `sender-${id}@example.test`, recipient: "contractor@example.test", subject, timestamp: "2026-08-15T12:00:00Z", textBody: body, attachments: [] });
const clientsFor = (jobs: JobberJob[]) => jobs.map(row => ({ id: row.clientId, name: row.title, email: `${row.id}@example.test` }));

type ExactInput = {
  id: number; name: string; sources: ScenarioFixture["manifest"]["connectedSources"];
  qb?: Partial<ScenarioFixture["quickbooks"]>; bank?: PlaidTransaction[]; manual?: ScenarioFixture["plaid"]["manualTransactions"];
  balance?: number; jobs?: JobberJob[]; emails?: GmailMessage[]; answer?: Partial<ScenarioAnswerKey>;
  sourceHealth?: ScenarioFixture["manifest"]["sourceHealth"];
};

function exact(input: ExactInput): { fixture: ScenarioFixture; answerKey: ScenarioAnswerKey } {
  const jobs = input.jobs ?? [];
  const qb = { invoices: [], deposits: [], purchases: [], ...input.qb } as ScenarioFixture["quickbooks"];
  const invoiced = new Set(qb.invoices.map(row => row.projectId).filter(Boolean));
  const unbilled = jobs.filter(row => (row.status === "completed" || row.status === "closed") && !invoiced.has(row.jobNumber));
  const fixture: ScenarioFixture = {
    manifest: { scenarioId: `${String(input.id).padStart(2, "0")}_CONTRACTOR_INTELLIGENCE`, scenarioName: input.name, industry: "Contracting", companyName: `Exact Scenario ${input.id} Contractor`, dateRange: { start, end }, connectedSources: input.sources, businessStory: input.name, expectedInsightKeys: [], prohibitedInsightKeys: [], sourceHealth: input.sourceHealth },
    quickbooks: qb,
    plaid: { institutionName: "Synthetic Test Bank", accounts: input.sources.includes("plaid") ? [{ id: "bank-checking", name: "Business Checking", type: "depository", subtype: "checking", currentBalance: input.balance ?? 0, availableBalance: input.balance ?? 0 }] : [], transactions: input.bank ?? [], manualTransactions: input.manual },
    jobber: { clients: clientsFor(jobs), jobs }, gmail: { messages: input.emails ?? [] },
  };
  return { fixture, answerKey: { completedUnbilledJobs: unbilled.map(row => ({ jobId: row.id, jobNumber: row.jobNumber, value: row.total })), completedUnbilledJobCount: unbilled.length, completedUnbilledValue: unbilled.reduce((sum, row) => sum + row.total, 0), ...input.answer } };
}

const s1Bank = [tx("zelle-mike",2400,"Zelle Mike Thompson","customer_payment"),tx("zelle-sarah",1250,"Zelle Sarah Lee","customer_payment"),tx("jose-pay",-875,"Jose Materials","business_expense"),tx("hd-642",-642.18,"Home Depot","business_expense"),tx("shell-9460",-94.60,"Shell","business_expense"),tx("verizon-138",-138,"Verizon","business_expense"),tx("savings-in",1500,"Transfer from savings","internal_transfer")];
const s2Invoices=[invoice("gf-1001",18000),invoice("gf-1002",7500)];
const s3Jobs=[job("j-101",9500,"completed","Wilson Home"),job("j-102",14000,"active","Rivera Property")]; s3Jobs[0].jobNumber="J-101"; s3Jobs[1].jobNumber="J-102";
s3Jobs[0].estimatedCosts = { materials: 2_000, labor: 2_500 };
const s4Jobs=[job("j-201",20000,"completed","Parker Renovations"),job("j-202",12000,"completed","Davis Homes"),job("j-203",17500,"active","Eastside Rentals")]; s4Jobs.forEach((j,i)=>j.jobNumber=`J-${201+i}`);

export const exactContractorIntelligenceScenarios = [
  exact({id:1,name:"Bank + Gmail Only with Zelle Activity",sources:["plaid","gmail"],bank:s1Bank,balance:15900.22,emails:[mail("mike-confirm","Mike Thompson payment $2,400"),mail("sarah-confirm","Sarah Lee payment $1,250"),mail("hd-receipt","Home Depot receipt $642.18"),mail("jose-invoice","Jose Materials invoice $875")],answer:{bankFacts:{inflows:5150,outflows:1749.78,netCashMovement:3400.22,currentCash:15900.22,availableCash:15900.22},expectedNumericValues:{startingCash:12500,likelyCustomerRevenue:3650},expectedMatches:[{id:"mike",recordIds:["zelle-mike","mike-confirm"],economicEvent:"revenue",expectedAmount:2400,confidence:"high",disposition:"matched"},{id:"home-depot",recordIds:["hd-642","hd-receipt"],economicEvent:"expense",expectedAmount:642.18,confidence:"high",disposition:"matched"}],prohibitedConclusions:["Savings transfer is revenue","Unsupported job assignment"]}}),
  exact({id:2,name:"Organized Contractor with Payroll and Contracts",sources:["plaid","quickbooks","gmail"],qb:{invoices:s2Invoices,payments:[{id:"pay-gf1",invoiceId:"gf-1001",date:"2026-08-01",amount:18000,customerName:"Greenfield Property Group"},{id:"pay-gf2",invoiceId:"gf-1002",date:"2026-08-01",amount:7500,customerName:"Greenfield Property Group"}],purchases:[{id:"abc-qb",date:"2026-08-01",amount:3450,vendor:"ABC Lumber",description:"Lumber"},{id:"payroll-qb",date:"2026-08-01",amount:6800,vendor:"Payroll",description:"Payroll"},{id:"insurance-qb",date:"2026-08-01",amount:1200,vendor:"Insurer",description:"Insurance"}]},bank:[tx("greenfield-18",18000,"Greenfield payment","customer_payment"),tx("greenfield-75",7500,"Greenfield second payment","customer_payment"),tx("payroll-bank",-6800,"Payroll","business_expense"),tx("abc-bank",-3450,"ABC Lumber ACH","business_expense"),tx("insurance-bank",-1200,"Insurance","business_expense")],balance:14050,emails:[mail("greenfield-contract","Signed Greenfield contract $25,500"),mail("payroll-confirm","Payroll confirmation $6,800"),mail("abc-invoice","ABC Lumber invoice $3,450"),mail("insurance-renewal","Insurance renewal $1,200")],answer:{expectedNumericValues:{contractValue:25500,paid:25500,payroll:6800,vendor:3450,insurance:1200},expectedDuplicates:[{economicEvent:"Greenfield payments",recordIds:["pay-gf1","pay-gf2","greenfield-18","greenfield-75","greenfield-contract"],expectedCount:2}]}}),
  exact({id:3,name:"QuickBooks + Jobber Only",sources:["quickbooks","jobber"],jobs:s3Jobs,qb:{invoices:[invoice("wilson-invoice",9500,0,"J-101")],payments:[{id:"wilson-payment",invoiceId:"wilson-invoice",date:"2026-08-01",amount:9500,customerName:"Wilson Home"}],purchases:[{id:"wilson-material",date:"2026-08-01",amount:2150,vendor:"Materials",description:"Wilson",jobNumber:"J-101"},{id:"wilson-sub",date:"2026-08-01",amount:2700,vendor:"Subcontractor",description:"Wilson",jobNumber:"J-101"},{id:"rivera-material",date:"2026-08-01",amount:3200,vendor:"Materials",description:"Rivera",jobNumber:"J-102"}]},answer:{expectedNumericValues:{wilsonEstimatedCost:4500,wilsonActualCost:4850,wilsonMargin:4650,riveraMaterials:3200}}}),
  exact({id:4,name:"All Four Sources Connected",sources:["plaid","quickbooks","jobber","gmail"],jobs:s4Jobs,qb:{invoices:[invoice("parker-invoice",20000,0,"J-201"),invoice("davis-invoice",12000,5000,"J-202"),invoice("eastside-deposit",8750,0,"J-203")],purchases:[{id:"parker-material",date:"2026-08-01",amount:5000,vendor:"Materials",description:"Parker",jobNumber:"J-201"},{id:"parker-labor",date:"2026-08-01",amount:4000,vendor:"Labor",description:"Parker",jobNumber:"J-201"},{id:"davis-material",date:"2026-08-01",amount:4500,vendor:"Materials",description:"Davis",jobNumber:"J-202"},{id:"davis-labor",date:"2026-08-01",amount:4200,vendor:"Labor",description:"Davis",jobNumber:"J-202"},{id:"eastside-material",date:"2026-08-01",amount:2100,vendor:"Materials",description:"Eastside",jobNumber:"J-203"}]},bank:[tx("parker-bank",20000,"Parker payment","customer_payment"),tx("davis-bank",7000,"Davis partial payment","customer_payment"),tx("eastside-bank",8750,"Eastside deposit","customer_payment"),tx("parker-cost-bank",-9000,"Parker vendors","business_expense"),tx("davis-cost-bank",-8700,"Davis vendors","business_expense"),tx("eastside-cost-bank",-2100,"Eastside materials","business_expense")],emails:[mail("parker-complete","Parker signed completion notice"),mail("davis-promise","Davis remaining $5,000 next week"),mail("eastside-contract","Eastside contract"),mail("material-receipts","Material receipts"),mail("sub-invoices","Subcontractor invoices")],answer:{expectedNumericValues:{parkerMargin:11000,davisReceivable:5000,eastsideDeposit:8750}}}),
  exact({id:5,name:"Duplicate and Conflicting Data",sources:["plaid","quickbooks","gmail"],qb:{invoices:[invoice("dup-invoice",5000)],payments:[{id:"dup-qb-payment",invoiceId:"dup-invoice",date:"2026-08-01",amount:5000,customerName:"Customer"}],purchases:[{id:"conflict-qb",date:"2026-08-02",amount:425,vendor:"Vendor",description:"Same expense"}]},bank:[tx("dup-bank",5000,"Customer deposit","customer_payment"),tx("conflict-bank",-420,"Vendor charge","business_expense","2026-08-02")],manual:[{...tx("dup-manual",5000,"Customer deposit","customer_payment"),statementId:"statement-1",originalTransactionId:"dup-bank"}],emails:[mail("dup-confirm","Payment confirmation $5,000"),mail("conflict-receipt","Vendor receipt $420")],answer:{expectedNumericValues:{economicRevenue:5000,bankExpense:420,accountingExpense:425,discrepancy:5},expectedDuplicates:[{economicEvent:"customer payment",recordIds:["dup-qb-payment","dup-bank","dup-manual","dup-confirm"],expectedCount:1}],expectedConflicts:[{id:"expense-discrepancy",recordIds:["conflict-qb","conflict-bank","conflict-receipt"],field:"amount",values:[420,425],requiredDisposition:"surface_for_review"}],severity:"Critical"}}),
  exact({id:6,name:"Unpaid Invoice / Receivable Risk",sources:["quickbooks","jobber","gmail"],jobs:[Object.assign(job("overdue-job",15000,"completed","Delayed Customer"),{jobNumber:"OVERDUE-1",completedAt:"2026-07-17"})],qb:{invoices:[invoice("overdue-invoice",15000,15000,"OVERDUE-1","2026-07-17")],purchases:[{id:"overdue-costs",date:"2026-07-01",amount:8500,vendor:"Job costs",description:"Costs",jobNumber:"OVERDUE-1"}]},emails:[mail("delay-email","Payment delayed two more weeks")],answer:{expectedNumericValues:{overdueReceivable:15000,jobCosts:8500,jobMargin:6500}}}),
  exact({id:7,name:"Completed but Unbilled Work",sources:["jobber","quickbooks"],jobs:[Object.assign(job("unbilled-job",8000),{jobNumber:"UNBILLED-1"})],qb:{purchases:[{id:"unbilled-cost",date:"2026-08-01",amount:3600,vendor:"Job costs",description:"Unbilled job",jobNumber:"UNBILLED-1"}]},answer:{expectedNumericValues:{unbilledWork:8000,associatedCosts:3600}}}),
  exact({id:8,name:"Loss-Making Job",sources:["plaid","quickbooks","jobber"],jobs:[job("job-a",10000),job("job-b",16000),job("job-c",9000)],qb:{invoices:[invoice("inv-a",10000,0,"JOB-A"),invoice("inv-b",16000,0,"JOB-B"),invoice("inv-c",9000,0,"JOB-C")],purchases:[{id:"cost-a",date:"2026-08-01",amount:5000,vendor:"Costs",description:"A",jobNumber:"JOB-A"},{id:"cost-b",date:"2026-08-01",amount:9000,vendor:"Costs",description:"B",jobNumber:"JOB-B"},{id:"cost-c",date:"2026-08-01",amount:10500,vendor:"Costs",description:"C",jobNumber:"JOB-C"}]},answer:{expectedNumericValues:{marginA:5000,marginB:7000,marginC:-1500}}}),
  exact({id:9,name:"Payroll and Cash Shortfall Risk",sources:["plaid","quickbooks","gmail"],balance:9000,qb:{liabilities:[{id:"payroll-liability",dueDate:"2026-09-03",amount:7200,payee:"Payroll",kind:"payroll",status:"open"},{id:"vendor-liability",dueDate:"2026-09-05",amount:4500,payee:"Vendor",kind:"vendor",status:"open"}],invoices:[invoice("future-payment",8000,8000,undefined,"2026-09-10")]},emails:[mail("payroll-notice","Payroll due $7,200"),mail("vendor-due","Vendor invoice due $4,500")],answer:{expectedNumericValues:{availableCash:9000,nearTermObligations:11700,shortfall:2700,futurePayment:8000}}}),
  exact({id:10,name:"Personal Transfer vs Business Revenue",sources:["plaid"],bank:[tx("customer-ach",4500,"Customer ACH","customer_payment"),tx("personal-in",3000,"Personal checking transfer","personal_transfer"),tx("savings-out",-2000,"Transfer to savings","internal_transfer"),tx("savings-back",2000,"Transfer from savings","internal_transfer"),tx("customer-check",1800,"Customer check","customer_payment")],balance:9300,answer:{bankFacts:{inflows:11300,outflows:2000,netCashMovement:9300,currentCash:9300,availableCash:9300},expectedNumericValues:{customerRevenue:6300}}}),
  exact({id:11,name:"Customer Concentration Risk",sources:["quickbooks","jobber"],jobs:[job("customer-a",120000),job("customer-b",20000),job("customer-c",15000),job("customer-d",10000)],qb:{invoices:[invoice("a-inv",120000,0,"CUSTOMER-A"),invoice("b-inv",20000,0,"CUSTOMER-B"),invoice("c-inv",15000,0,"CUSTOMER-C"),invoice("d-inv",10000,0,"CUSTOMER-D")]},answer:{expectedNumericValues:{totalRevenue:165000,customerARevenue:120000,customerASharePercent:72.7272727}}}),
  exact({id:12,name:"Missing Sources / Graceful Degradation",sources:["plaid","jobber","gmail"],jobs:[job("available-job",5000,"active")],bank:[tx("available-deposit",2500,"Customer deposit","customer_payment"),tx("available-expense",-750,"Materials","business_expense")],balance:1750,emails:[mail("available-receipt","Materials receipt $750")],sourceHealth:{quickbooks:{status:"error",stale:true}},answer:{expectedConfidenceIssues:[{subject:"accounting confirmation",expected:"limited",reason:"QuickBooks unavailable"}],prohibitedConclusions:["Invented QuickBooks value"]}}),
  exact({id:13,name:"Ambiguous Job Matching",sources:["plaid","jobber","gmail"],jobs:[Object.assign(job("j-301",6000,"active","Smith Kitchen"),{jobNumber:"J-301"}),Object.assign(job("j-302",6200,"active","Smith Bathroom"),{jobNumber:"J-302"})],bank:[tx("smith-charge",-1100,"Smith project materials","business_expense")],balance:-1100,emails:[mail("smith-receipt","Smith project materials $1,100")],answer:{expectedMatches:[{id:"ambiguous-smith",recordIds:["smith-charge","smith-receipt","j-301","j-302"],economicEvent:"job_cost",expectedAmount:1100,confidence:"ambiguous",disposition:"manual_review"}],expectedNumericValues:{unassignedExpense:1100}}}),
  exact({id:14,name:"Stale or Delayed Integration Data",sources:["plaid","quickbooks","jobber"],jobs:[Object.assign(job("stale-job",11000),{jobNumber:"STALE-1"})],qb:{invoices:[invoice("stale-invoice",11000,11000,"STALE-1")]},bank:[tx("today-payment",11000,"Customer payment","customer_payment","2026-08-31")],balance:11000,sourceHealth:{quickbooks:{stale:true,status:"active"}},answer:{expectedMatches:[{id:"possible-sync-delay",recordIds:["today-payment","stale-invoice","stale-job"],economicEvent:"revenue",expectedAmount:11000,confidence:"medium",disposition:"matched"}],expectedConflicts:[{id:"freshness",recordIds:["today-payment","stale-invoice"],field:"payment status",values:["bank received today","QuickBooks unpaid and one day stale"],requiredDisposition:"wait_for_freshness"}]}}),
  exact({id:15,name:"Refund / Reversal Handling",sources:["plaid","quickbooks"],qb:{invoices:[invoice("refund-invoice",6000,1500)],payments:[{id:"refund-payment",invoiceId:"refund-invoice",date:"2026-08-01",amount:6000,customerName:"Customer"}],credits:[{id:"refund-credit",invoiceId:"refund-invoice",paymentId:"refund-payment",date:"2026-08-02",amount:1500,customerName:"Customer",reason:"refund"}]},bank:[tx("payment-6000",6000,"Customer payment","customer_payment"),{...tx("refund-1500",-1500,"Customer refund","refund","2026-08-02"),relatedTransactionId:"payment-6000"}],balance:4500,answer:{expectedNumericValues:{grossPayment:6000,refund:1500,netCollectedCash:4500},expectedMatches:[{id:"payment-refund",recordIds:["payment-6000","refund-1500","refund-payment","refund-credit"],economicEvent:"refund",expectedAmount:4500,confidence:"high",disposition:"matched"}]}}),
  exact({id:16,name:"Contractor with Sparse Evidence",sources:["plaid","gmail"],bank:Array.from({length:25},(_,i)=>tx(`sparse-${i+1}`,i===0?1200:i===1?800:i<5?-100: i<8?-200:-(20+i),i===0?"Clear customer":i<3?"Unclear Zelle":i<8?"Cash withdrawal":"Unclassified",i===0?"customer_payment":i<3?"unknown":i<8?"cash_withdrawal":"unknown")),balance:0,emails:Array.from({length:5},(_,i)=>mail(`sparse-mail-${i+1}`,i===0?"Clear customer payment confirmation":"Supporting receipt")),answer:{expectedNumericValues:{transactions:25,supportedTransactions:5},expectedConfidenceIssues:[{subject:"unsupported classifications",expected:"low",reason:"Only 5 of 25 transactions have email evidence"}],prohibitedConclusions:["Invented job name","Invented customer relationship"]}}),
] as const;

export function exactContractorScenarioById(scenarioId: string) {
  return exactContractorIntelligenceScenarios.find(entry => entry.fixture.manifest.scenarioId === scenarioId);
}
