import { Router, type IRouter } from "express";
import healthRouter from "./health";
import openaiChatRouter from "./openai-chat";
import stripeRouter from "./stripe";
import extractDocumentRouter from "./extract-document";
import scanStatementRouter from "./scan-statement";
import extractTextRouter from "./extract-text";
import cleanPlTransactionsRouter from "./clean-pl-transactions";
import documentProxyRouter from "./document-proxy";
import documentUploadRouter from "./document-upload";
import documentDownloadRouter from "./document-download";
import documentDeleteRouter from "./document-delete";
import chatUploadRouter from "./chat-upload";
import planLimitsRouter from "./plan-limits";
import adminRouter from "./admin";
import plaidRouter from "./plaid";
import tokenUnlocksRouter from "./token-unlocks";
import referralsRouter from "./referrals";
import financialStatementsRouter from "./financial-statements";
import businessDocumentRouter from "./business-document";
import avatarRouter from "./avatar";
import cpaOrdersRouter from "./cpa-orders";
import cpaMonitoringRouter from "./cpa-monitoring";
import cpaClientFinancialsRouter from "./cpa-client-financials";
import authProfileRouter from "./auth-profile";
import quickbooksRouter from "./quickbooks";
import monitoringRouter from "./monitoring";
import monitoringJobsRouter from "./monitoring-jobs";
import connectionStatusRouter from "./connection-status";
import jobberRouter from "./jobber";
import financialInputsRouter from "./financial-inputs";
import financialSummaryRouter from "./financial-summary";

const router: IRouter = Router();

router.use(healthRouter);
router.use(openaiChatRouter);
router.use(stripeRouter);
router.use(extractDocumentRouter);
router.use(scanStatementRouter);
router.use(extractTextRouter);
router.use(cleanPlTransactionsRouter);
router.use(documentProxyRouter);
router.use(documentUploadRouter);
router.use(documentDownloadRouter);
router.use(documentDeleteRouter);
router.use(chatUploadRouter);
router.use(planLimitsRouter);
router.use(adminRouter);
router.use(plaidRouter);
router.use(tokenUnlocksRouter);
router.use(referralsRouter);
router.use(financialStatementsRouter);
router.use(businessDocumentRouter);
router.use(avatarRouter);
router.use(cpaOrdersRouter);
router.use(cpaMonitoringRouter);
router.use(cpaClientFinancialsRouter);
router.use(authProfileRouter);
router.use(quickbooksRouter);
router.use(monitoringRouter);
router.use(monitoringJobsRouter);
router.use(connectionStatusRouter);
router.use(jobberRouter);
router.use(financialInputsRouter);
router.use(financialSummaryRouter);

export default router;
