import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link } from "wouter";
import { ArrowLeft, CalendarDays, CheckCircle2, Landmark, Loader2, Plus, ReceiptText, ShieldCheck, Trash2, WalletCards } from "lucide-react";
import { toast } from "sonner";
import { useMonitoringOrganization } from "@/hooks/use-monitoring-organization";
import { authenticatedApi, apiErrorMessage } from "@/lib/authenticated-api";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

type PlanningItem = { id: number; item_type: "obligation" | "receivable" | "filing_schedule"; name: string; amount: number | null; due_date: string; recurrence: string; status: string };
type Settings = { payroll_amount: number | null; payroll_cadence: string | null; next_payroll_date: string | null; operating_buffer: number | null; tax_effective_rate: number | null; projected_taxable_income: number | null; tax_amount_set_aside: number | null; updated_at?: string | null };
type ForecastEvent = { key: string; date: string; label: string; type: string; amount: number; projectedBalance: number };
type Readiness = { available: boolean; missingInputs?: string[]; safeToSpend?: number; shortfall?: number; shortfallDate?: string | null; cashAvailable?: number; knownObligations?: number; payrollRequirement?: number; taxReserveRequirement?: number; operatingBuffer?: number; estimatedReserve?: number | null; amountSetAside?: number | null; remainingReserve?: number | null; disclaimer?: string; openingCash?: number; endingCash?: number; lowestBalance?: number; lowestBalanceDate?: string; totalCashIn?: number; totalCashOut?: number; events?: ForecastEvent[] };
type Data = { settings: Settings | null; items: PlanningItem[]; verified_cash: { available: boolean; amount: number | null; account_count: number; refreshed_at: string | null; freshness_hours: number }; readiness: Record<string, Readiness> };
const emptySettings = { payroll_amount: "", payroll_cadence: "", next_payroll_date: "", operating_buffer: "", tax_effective_rate: "", projected_taxable_income: "", tax_amount_set_aside: "" };
const labels: Record<string, string> = { cashAvailable: "verified cash balance", fresh_account_balance: "fresh connected-account balance", knownObligations: "known obligations", payrollRequirement: "payroll", operatingBuffer: "operating buffer", taxReserveRequirement: "calculated tax reserve", tax_strategy: "filing schedule", effective_rate: "effective tax rate", projected_taxable_income: "projected taxable income", reserved_funds: "funds already reserved", recurringTransactions: "recurring transaction history", payroll: "payroll schedule", receivables: "expected receivables" };

export default function FinancialInputs() {
  const organization = useMonitoringOrganization(); const orgId = organization.data?.id ?? null; const queryClient = useQueryClient();
  const [form, setForm] = useState<Record<string, string>>(emptySettings);
  const [savedForm, setSavedForm] = useState(JSON.stringify(emptySettings));
  const [savedAt, setSavedAt] = useState<string | null>(null);
  const [item, setItem] = useState({ item_type: "obligation", name: "", amount: "", due_date: "", recurrence: "none" });
  const query = useQuery<Data>({ queryKey: ["financial-inputs", orgId], enabled: orgId !== null, queryFn: async () => { const response = await authenticatedApi(`/api/financial-inputs?organization_id=${orgId}`); if (!response.ok) throw new Error(await apiErrorMessage(response, "Could not load planning inputs.")); return response.json(); } });
  useEffect(() => { if (!query.data) return; const value = query.data.settings; const loaded = value ? Object.fromEntries(Object.keys(emptySettings).map(key => [key, value[key as keyof Settings] == null ? "" : String(value[key as keyof Settings])])) : emptySettings; setForm(loaded); setSavedForm(JSON.stringify(loaded)); setSavedAt(value?.updated_at ?? null); }, [query.data]);
  const hasUnsavedSettings = JSON.stringify(form) !== savedForm;
  const refresh = () => queryClient.invalidateQueries({ queryKey: ["financial-inputs", orgId] });
  const save = useMutation({ mutationFn: async () => { const response = await authenticatedApi("/api/financial-inputs/settings", { method: "PUT", body: JSON.stringify({ organization_id: orgId, ...form }) }); if (!response.ok) throw new Error(await apiErrorMessage(response, "Could not save settings.")); return response.json(); }, onSuccess: (result: { settings?: Settings }) => { setSavedForm(JSON.stringify(form)); setSavedAt(result.settings?.updated_at ?? new Date().toISOString()); toast.success("Planning settings saved"); refresh(); }, onError: (error: Error) => toast.error(error.message) });
  const add = useMutation({ mutationFn: async () => { const response = await authenticatedApi("/api/financial-inputs/items", { method: "POST", body: JSON.stringify({ organization_id: orgId, ...item }) }); if (!response.ok) throw new Error(await apiErrorMessage(response, "Could not add input.")); return response.json(); }, onSuccess: () => { toast.success("Planning input added"); setItem(current => ({ ...current, name: "", amount: "", due_date: "" })); refresh(); }, onError: (error: Error) => toast.error(error.message) });
  const remove = useMutation({ mutationFn: async (id: number) => { const response = await authenticatedApi(`/api/financial-inputs/items/${id}?organization_id=${orgId}`, { method: "DELETE" }); if (!response.ok) throw new Error(await apiErrorMessage(response, "Could not remove input.")); }, onSuccess: () => { toast.success("Planning input removed"); refresh(); }, onError: (error: Error) => toast.error(error.message) });
  if (organization.isLoading || query.isLoading) return <div className="flex min-h-[420px] items-center justify-center"><Loader2 className="h-7 w-7 animate-spin text-primary" /></div>;
  if (!orgId || query.isError) return <div className="p-6"><Card><CardContent className="p-6">Planning inputs are unavailable. No financial calculations were changed.</CardContent></Card></div>;
  return <div className="monitoring-page w-full max-w-none space-y-4 lg:space-y-6">
    <header className="space-y-3"><Button asChild variant="ghost" size="sm" className="-ml-3"><Link href="/user/settings"><ArrowLeft className="mr-2 h-4 w-4" />Settings</Link></Button><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-2xl font-bold tracking-tight sm:text-3xl">Financial planning inputs</h1><p className="mt-1 max-w-3xl text-sm text-muted-foreground">Configure <span className="font-medium text-foreground">{organization.data?.name}</span>. These planning inputs never change your accounting records.</p></div><div className="flex w-fit items-center gap-2 rounded-full border bg-muted/40 px-3 py-1.5 text-xs text-muted-foreground"><ShieldCheck className="h-4 w-4 text-emerald-500" />Organization-specific</div></div></header>
    <Card className="overflow-hidden"><CardHeader className="border-b bg-muted/20"><CardTitle className="flex items-center gap-2"><Landmark className="h-5 w-5 text-primary" />Feature readiness</CardTitle><CardDescription>Each result appears only when every required input passes validation.</CardDescription></CardHeader><CardContent className="grid items-stretch gap-4 p-4 sm:p-6 lg:grid-cols-3">{Object.entries(query.data?.readiness ?? {}).map(([key, value]) => <ReadinessCard key={key} feature={key} value={value} data={query.data!} />)}</CardContent></Card>
    <div className="grid items-stretch gap-6 xl:grid-cols-2">
      <Card className="flex h-full flex-col"><CardHeader className="border-b"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><CardTitle className="flex items-center gap-2"><WalletCards className="h-5 w-5 text-primary" />Payroll and reserves</CardTitle><CardDescription className="mt-1.5">Enter confirmed planning assumptions for this organization.</CardDescription></div><div className={`flex w-fit items-center gap-1.5 rounded-full border px-2.5 py-1 text-xs ${hasUnsavedSettings ? "border-amber-500/30 bg-amber-500/10 text-amber-500" : "border-emerald-500/30 bg-emerald-500/10 text-emerald-500"}`}><CheckCircle2 className="h-3.5 w-3.5" />{hasUnsavedSettings ? "Unsaved changes" : savedAt ? "Saved" : "Not configured"}</div></div>{savedAt && !hasUnsavedSettings && <p className="mt-2 text-xs text-muted-foreground">Last saved {new Date(savedAt).toLocaleString()}</p>}</CardHeader><CardContent className="grid flex-1 content-start gap-x-5 gap-y-4 p-5 [&_button[role=combobox]]:h-10 sm:grid-cols-2 sm:p-6">
        <Field label="Payroll amount" value={form.payroll_amount} onChange={value => setForm({ ...form, payroll_amount: value })} type="number" />
        <div><Label text="Payroll cadence" /><Select value={form.payroll_cadence || "unset"} onValueChange={value => setForm({ ...form, payroll_cadence: value === "unset" ? "" : value })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="unset">Not configured</SelectItem><SelectItem value="weekly">Weekly</SelectItem><SelectItem value="biweekly">Every two weeks</SelectItem><SelectItem value="semimonthly">Twice monthly</SelectItem><SelectItem value="monthly">Monthly</SelectItem></SelectContent></Select></div>
        <Field label="Next payroll date" value={form.next_payroll_date} onChange={value => setForm({ ...form, next_payroll_date: value })} type="date" />
        <Field label="Operating buffer" value={form.operating_buffer} onChange={value => setForm({ ...form, operating_buffer: value })} type="number" />
        <Field label="Effective tax rate (%)" value={form.tax_effective_rate} onChange={value => setForm({ ...form, tax_effective_rate: value })} type="number" />
        <Field label="Projected taxable income" value={form.projected_taxable_income} onChange={value => setForm({ ...form, projected_taxable_income: value })} type="number" />
        <Field label="Tax funds already set aside" value={form.tax_amount_set_aside} onChange={value => setForm({ ...form, tax_amount_set_aside: value })} type="number" />
        <div className="flex items-end sm:col-span-2"><Button className="w-full sm:ml-auto sm:w-48" onClick={() => save.mutate()} disabled={save.isPending || !hasUnsavedSettings}>{save.isPending ? <Loader2 className="animate-spin" /> : <CheckCircle2 />}{hasUnsavedSettings ? "Save settings" : "Saved"}</Button></div>
      </CardContent></Card>
      <Card className="flex h-full flex-col"><CardHeader className="border-b"><CardTitle className="flex items-center gap-2"><ReceiptText className="h-5 w-5 text-primary" />Add planning item</CardTitle><CardDescription>Track obligations, expected receivables, and verified filing dates.</CardDescription></CardHeader><CardContent className="grid flex-1 content-start gap-x-5 gap-y-4 p-5 [&_button[role=combobox]]:h-10 sm:grid-cols-2 sm:p-6">
        <div className="sm:col-span-2"><Label text="Input type" /><Select value={item.item_type} onValueChange={value => setItem({ ...item, item_type: value })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="obligation">Cash obligation</SelectItem><SelectItem value="receivable">Expected receivable</SelectItem><SelectItem value="filing_schedule">Tax filing date</SelectItem></SelectContent></Select></div>
        <div className="sm:col-span-2"><Field label="Name" value={item.name} onChange={value => setItem({ ...item, name: value })} /></div>
        <Field label={item.item_type === "filing_schedule" ? "Expected payment (optional)" : "Amount"} value={item.amount} onChange={value => setItem({ ...item, amount: value })} type="number" /><Field label="Due date" value={item.due_date} onChange={value => setItem({ ...item, due_date: value })} type="date" />
        <div><Label text="Repeats" /><Select value={item.recurrence} onValueChange={value => setItem({ ...item, recurrence: value })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["none","weekly","monthly","quarterly","yearly"].map(value => <SelectItem key={value} value={value} className="capitalize">{value}</SelectItem>)}</SelectContent></Select></div>
        <div className="flex items-end"><Button className="w-full" onClick={() => add.mutate()} disabled={add.isPending || !item.name || !item.due_date}>{add.isPending ? <Loader2 className="animate-spin" /> : <Plus />}Add input</Button></div>
      </CardContent></Card>
    </div>
    {query.data?.readiness.forecast?.available && <ForecastPanel forecast={query.data.readiness.forecast} />}
    <Card><CardHeader className="border-b"><CardTitle className="flex items-center gap-2"><CalendarDays className="h-5 w-5 text-primary" />Configured inputs</CardTitle><CardDescription>{query.data?.items.length ?? 0} planning item{query.data?.items.length === 1 ? "" : "s"} for this organization</CardDescription></CardHeader><CardContent className="grid gap-3 p-4 sm:p-6 lg:grid-cols-2">{query.data?.items.length ? query.data.items.map(row => <div key={row.id} className="flex min-h-20 items-center gap-3 rounded-xl border bg-muted/10 p-4"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-emerald-500/10"><CheckCircle2 className="h-5 w-5 text-emerald-500" /></div><div className="min-w-0 flex-1"><p className="truncate font-medium">{row.name}</p><p className="mt-1 text-xs text-muted-foreground capitalize">{row.item_type.replaceAll("_", " ")} · due {new Date(`${row.due_date}T00:00:00`).toLocaleDateString()} · {row.recurrence}{row.amount == null ? "" : ` · ${currency.format(row.amount)}`}</p></div><Button variant="ghost" size="icon" aria-label={`Remove ${row.name}`} onClick={() => remove.mutate(row.id)} disabled={remove.isPending}><Trash2 className="h-4 w-4 text-muted-foreground" /></Button></div>) : <p className="text-sm text-muted-foreground lg:col-span-2">No obligations, receivables, or filing dates configured yet.</p>}</CardContent></Card>
  </div>;
}
function Label({ text }: { text: string }) { return <p className="mb-1.5 text-sm font-medium leading-5">{text}</p>; }
function Field({ label, value, onChange, type = "text" }: { label: string; value: string; onChange: (value: string) => void; type?: string }) { return <div className="min-w-0"><Label text={label} /><Input className="h-10" type={type} min={type === "number" ? 0 : undefined} step={type === "number" ? "0.01" : undefined} value={value} onChange={event => onChange(event.target.value)} /></div>; }
const currency = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" });
function ReadinessCard({ feature, value, data }: { feature: string; value: Readiness; data: Data }) {
  const safe = feature === "safe_to_spend"; const tax = feature === "tax_reserve";
  const Icon = safe ? WalletCards : tax ? ShieldCheck : CalendarDays;
  return <div className="flex h-full min-h-52 flex-col rounded-xl border bg-card p-5 shadow-sm"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10"><Icon className="h-5 w-5 text-primary" /></div><p className="font-semibold capitalize">{feature.replaceAll("_", " ")}</p></div><div className="mt-4 flex-1">
    {safe && value.available && value.safeToSpend != null ? <><p className="mt-1 text-xl font-bold text-emerald-500">{currency.format(value.safeToSpend)}</p>{Boolean(value.shortfall) && <p className="mt-1 text-sm font-medium text-amber-500">{currency.format(value.shortfall!)} cash shortfall</p>}</> : tax && value.available && value.remainingReserve != null ? <><p className="mt-1 text-xl font-bold text-emerald-500">{currency.format(value.remainingReserve)} remaining</p><p className="text-xs text-muted-foreground">Estimated reserve {currency.format(value.estimatedReserve ?? 0)}</p></> : <p className={value.available ? "mt-1 text-sm text-emerald-500" : "mt-1 text-sm text-amber-500"}>{value.available ? "Ready" : "More information needed"}</p>}
    {!value.available && <p className="mt-2 text-xs text-muted-foreground">{(value.missingInputs ?? []).map(input => labels[input] ?? input).join(", ")}</p>}
    {safe && data.verified_cash.available && <p className="mt-2 text-xs text-muted-foreground">Verified cash: {currency.format(data.verified_cash.amount ?? 0)} · {data.verified_cash.account_count} account{data.verified_cash.account_count === 1 ? "" : "s"} · refreshed {new Date(data.verified_cash.refreshed_at!).toLocaleString()}</p>}
    </div>{safe && value.available && <details className="mt-4 border-t pt-3 text-xs"><summary className="cursor-pointer font-medium text-primary">How this was calculated</summary><div className="mt-3 space-y-2 text-muted-foreground"><Breakdown label="Verified cash" value={value.cashAvailable} /><Breakdown label="Known obligations" value={value.knownObligations} negative /><Breakdown label="Next payroll" value={value.payrollRequirement} negative /><Breakdown label="Remaining tax reserve" value={value.taxReserveRequirement} negative /><Breakdown label="Operating buffer" value={value.operatingBuffer} negative /></div></details>}
    {tax && value.available && <details className="mt-4 border-t pt-3 text-xs"><summary className="cursor-pointer font-medium text-primary">How this was calculated</summary><div className="mt-3 space-y-2 text-muted-foreground"><Breakdown label="Estimated reserve" value={value.estimatedReserve ?? undefined} /><Breakdown label="Already set aside" value={value.amountSetAside ?? undefined} negative /><Breakdown label="Remaining reserve" value={value.remainingReserve ?? undefined} /></div><p className="mt-3 text-[11px] text-muted-foreground">{value.disclaimer}</p></details>}
  </div>;
}
function Breakdown({ label, value = 0, negative = false }: { label: string; value?: number; negative?: boolean }) { return <div className="flex justify-between gap-3"><span>{label}</span><span className="font-medium text-foreground">{negative ? "−" : ""}{currency.format(value)}</span></div>; }
function ForecastPanel({ forecast }: { forecast: Readiness }) {
  const events = forecast.events ?? [];
  return <Card><CardHeader className="border-b"><CardTitle className="flex items-center gap-2"><CalendarDays className="h-5 w-5 text-primary" />30-day cash forecast</CardTitle><CardDescription>Projected from verified cash and your dated planning inputs. This is not an accounting statement.</CardDescription></CardHeader><CardContent className="space-y-5 p-4 sm:p-6"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><ForecastMetric label="Opening cash" value={forecast.openingCash} /><ForecastMetric label="Expected cash in" value={forecast.totalCashIn} tone="positive" /><ForecastMetric label="Expected cash out" value={forecast.totalCashOut} tone="negative" /><ForecastMetric label="Projected ending cash" value={forecast.endingCash} tone={(forecast.endingCash ?? 0) < 0 ? "negative" : "positive"} /></div><div className={`rounded-xl border p-4 ${(forecast.shortfall ?? 0) > 0 ? "border-amber-500/30 bg-amber-500/10" : "border-emerald-500/30 bg-emerald-500/10"}`}><p className="font-semibold">Lowest projected balance: {currency.format(forecast.lowestBalance ?? 0)}</p><p className="mt-1 text-sm text-muted-foreground">Expected on {forecast.lowestBalanceDate ? new Date(`${forecast.lowestBalanceDate}T00:00:00`).toLocaleDateString() : "—"}{(forecast.shortfall ?? 0) > 0 ? ` · ${currency.format(forecast.shortfall!)} shortfall` : " · no projected shortfall"}</p></div><div className="overflow-hidden rounded-xl border"><div className="grid grid-cols-[90px_1fr_auto] gap-3 border-b bg-muted/30 px-4 py-3 text-xs font-medium text-muted-foreground sm:grid-cols-[110px_1fr_auto_auto]"><span>Date</span><span>Activity</span><span className="hidden sm:block">Change</span><span>Balance</span></div>{events.length ? events.map(event => <div key={event.key} className="grid grid-cols-[90px_1fr_auto] items-center gap-3 border-b px-4 py-3 text-sm last:border-b-0 sm:grid-cols-[110px_1fr_auto_auto]"><span className="text-xs text-muted-foreground">{new Date(`${event.date}T00:00:00`).toLocaleDateString([], { month: "short", day: "numeric" })}</span><div className="min-w-0"><p className="truncate font-medium">{event.label}</p><p className="text-xs capitalize text-muted-foreground">{event.type.replaceAll("_", " ")}</p></div><span className={`hidden font-medium sm:block ${event.amount >= 0 ? "text-emerald-500" : "text-rose-500"}`}>{event.amount >= 0 ? "+" : "−"}{currency.format(Math.abs(event.amount))}</span><span className={`font-semibold ${event.projectedBalance < 0 ? "text-rose-500" : ""}`}>{currency.format(event.projectedBalance)}</span></div>) : <p className="p-5 text-sm text-muted-foreground">No cash events fall within the next 30 days.</p>}</div></CardContent></Card>;
}
function ForecastMetric({ label, value = 0, tone }: { label: string; value?: number; tone?: "positive" | "negative" }) { return <div className="rounded-xl border bg-muted/10 p-4"><p className="text-xs text-muted-foreground">{label}</p><p className={`mt-1 text-xl font-bold ${tone === "positive" ? "text-emerald-500" : tone === "negative" ? "text-rose-500" : ""}`}>{currency.format(value)}</p></div>; }
