import { readFileSync } from "node:fs";
import { createRequire } from "node:module";
import assert from "node:assert/strict";
import test from "node:test";

const require = createRequire(new URL("../../.tmp/transaction-policy-validation/package.json", import.meta.url));
const { PGlite } = require("@electric-sql/pglite");
const migration = readFileSync(new URL("../../artifacts/booksmart/supabase/20260908_owner_account_deletion.sql", import.meta.url), "utf8");
const cpaMigration = readFileSync(new URL("../../artifacts/booksmart/supabase/20260909_cpa_account_deletion.sql", import.meta.url), "utf8");
const a = "00000000-0000-4000-8000-000000000001";
const b = "00000000-0000-4000-8000-000000000002";
const c = "00000000-0000-4000-8000-000000000003";

async function fixture() {
  const db = new PGlite();
  await db.exec(`
    CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role;
    CREATE SCHEMA auth; CREATE TABLE auth.users(id uuid PRIMARY KEY);
    CREATE TABLE users(id bigint PRIMARY KEY,auth_id uuid REFERENCES auth.users(id),role text,email text);
    CREATE TABLE organizations(id bigint PRIMARY KEY,owner_id bigint REFERENCES users(id) ON DELETE CASCADE);
    CREATE TABLE transactions(id bigint PRIMARY KEY,org_id bigint REFERENCES organizations(id) ON DELETE CASCADE);
    CREATE TABLE account_activity_notifications(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,organization_id bigint REFERENCES organizations(id) ON DELETE CASCADE);
    CREATE FUNCTION notify_transaction_delete() RETURNS trigger LANGUAGE plpgsql AS $$
      BEGIN INSERT INTO public.account_activity_notifications(organization_id) VALUES(OLD.org_id); RETURN OLD; END $$;
    CREATE TRIGGER transaction_delete_notice AFTER DELETE ON transactions FOR EACH ROW EXECUTE FUNCTION notify_transaction_delete();
    CREATE TABLE contractor_job_cost_assignments(id bigint PRIMARY KEY,organization_id bigint REFERENCES organizations(id) ON DELETE CASCADE);
    CREATE FUNCTION notify_job_cost_delete() RETURNS trigger LANGUAGE plpgsql AS $$
      BEGIN INSERT INTO public.account_activity_notifications(organization_id) VALUES(OLD.organization_id); RETURN OLD; END $$;
    CREATE TRIGGER job_cost_delete_notice AFTER DELETE ON contractor_job_cost_assignments FOR EACH ROW EXECUTE FUNCTION notify_job_cost_delete();
    CREATE TABLE jobber_expense_write_audit(id bigint PRIMARY KEY,organization_id bigint REFERENCES organizations(id) ON DELETE CASCADE,
      assignment_id bigint REFERENCES contractor_job_cost_assignments(id) ON DELETE RESTRICT,requested_by bigint REFERENCES users(id) ON DELETE RESTRICT);
    CREATE TABLE user_documents(id bigint PRIMARY KEY,user_id bigint REFERENCES users(id) ON DELETE CASCADE);
    CREATE TABLE token_transactions(id bigint PRIMARY KEY,user_id uuid REFERENCES auth.users(id));
    CREATE TABLE feature_unlocks(id bigint PRIMARY KEY,user_id uuid REFERENCES auth.users(id));
    CREATE TABLE subscriptions(id bigint PRIMARY KEY,user_id uuid REFERENCES auth.users(id));
    INSERT INTO auth.users VALUES ('${a}'),('${b}');
    INSERT INTO users VALUES (1,'${a}','user','a@test'),(2,'${b}','user','b@test');
    INSERT INTO organizations VALUES (10,1),(20,2);
    INSERT INTO transactions VALUES (100,10),(200,20);
    INSERT INTO contractor_job_cost_assignments VALUES (1000,10),(2000,20);
    INSERT INTO jobber_expense_write_audit VALUES (3000,10,1000,1),(4000,20,2000,2);
    INSERT INTO user_documents VALUES (5000,1),(6000,2);
    INSERT INTO token_transactions VALUES (1,'${a}'),(2,'${b}');
    INSERT INTO feature_unlocks VALUES (1,'${a}'),(2,'${b}');
    INSERT INTO subscriptions VALUES (1,'${a}'),(2,'${b}');
  `);
  await db.exec(migration);
  await db.exec(cpaMigration);
  return db;
}

test("account database deletion is complete, scoped, and repeat-safe", async () => {
  const db = await fixture();
  try {
    const result = await db.query(`SELECT delete_owner_account_data('${a}') AS id`);
    assert.equal(Number(result.rows[0].id), 1);
    for (const table of ["users", "organizations", "transactions", "contractor_job_cost_assignments", "jobber_expense_write_audit", "user_documents", "token_transactions", "feature_unlocks", "subscriptions"]) {
      const count = await db.query(`SELECT count(*)::int AS n FROM ${table}`);
      assert.equal(count.rows[0].n, 1, `${table} preserved a foreign tenant and deleted A`);
    }
    await assert.rejects(db.query(`SELECT delete_owner_account_data('${a}')`), /ordinary owner account not found/);
  } finally { await db.close(); }
});

test("an unexpected restrictive dependency rolls the entire database deletion back", async () => {
  const db = await fixture();
  try {
    await db.exec("CREATE TABLE deletion_blocker(id bigint PRIMARY KEY,user_id bigint REFERENCES users(id) ON DELETE RESTRICT); INSERT INTO deletion_blocker VALUES (1,1)");
    await assert.rejects(db.query(`SELECT delete_owner_account_data('${a}')`));
    for (const table of ["users", "organizations", "transactions", "token_transactions", "feature_unlocks", "subscriptions"]) {
      const count = await db.query(`SELECT count(*)::int AS n FROM ${table}`);
      assert.equal(count.rows[0].n, 2, `${table} was partially deleted`);
    }
  } finally { await db.close(); }
});

test("CPA identities cannot be deleted through the owner function", async () => {
  const db = await fixture();
  try {
    await db.exec("UPDATE users SET role='cpa' WHERE id=1");
    await assert.rejects(db.query(`SELECT delete_owner_account_data('${a}')`), /ordinary owner account not found/);
  } finally { await db.close(); }
});

test("CPA deletion removes engagements and attribution while preserving every client tenant", async () => {
  const db = await fixture();
  try {
    await db.exec(`
      INSERT INTO auth.users VALUES ('${c}');
      INSERT INTO users VALUES (3,'${c}','cpa','cpa@test');
      ALTER TABLE users ADD COLUMN referred_by_cpa_id bigint REFERENCES users(id) ON DELETE SET NULL;
      UPDATE users SET referred_by_cpa_id=3 WHERE id=1;
      CREATE TABLE orders(id bigint PRIMARY KEY,user_id bigint REFERENCES users(id) ON DELETE CASCADE,cpa_id bigint REFERENCES users(id) ON DELETE CASCADE);
      CREATE TABLE cpa_client_access(id bigint PRIMARY KEY,client_id bigint REFERENCES users(id) ON DELETE CASCADE,cpa_id bigint REFERENCES users(id) ON DELETE CASCADE);
      INSERT INTO orders VALUES (7000,1,3);
      INSERT INTO cpa_client_access VALUES (8000,1,3);
      INSERT INTO jobber_expense_write_audit VALUES (5000,10,1000,3);
    `);
    const result = await db.query(`SELECT delete_cpa_account_data('${c}') AS id`);
    assert.equal(Number(result.rows[0].id), 3);
    for (const table of ["organizations", "transactions", "contractor_job_cost_assignments", "user_documents"]) {
      const count = await db.query(`SELECT count(*)::int AS n FROM ${table}`);
      assert.equal(count.rows[0].n, 2, `${table} lost client-owned records`);
    }
    assert.equal((await db.query("SELECT count(*)::int AS n FROM orders")).rows[0].n, 0);
    assert.equal((await db.query("SELECT count(*)::int AS n FROM cpa_client_access")).rows[0].n, 0);
    assert.equal((await db.query("SELECT referred_by_cpa_id FROM users WHERE id=1")).rows[0].referred_by_cpa_id, null);
    assert.equal((await db.query("SELECT count(*)::int AS n FROM jobber_expense_write_audit WHERE requested_by=3")).rows[0].n, 0);
  } finally { await db.close(); }
});
