-- Isolated operational snapshots for the read-only Jobber integration.
-- These tables intentionally have no relationship to accounting transactions or reports.
ALTER TABLE public.jobber_connections
  ADD COLUMN IF NOT EXISTS refresh_generation BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS api_version_warning TEXT;

CREATE TABLE IF NOT EXISTS public.jobber_sync_state (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  connection_id BIGINT NOT NULL REFERENCES public.jobber_connections(id) ON DELETE CASCADE,
  object_type TEXT NOT NULL CHECK (object_type IN ('clients','jobs','scheduled_items','quotes','invoices','payments')),
  status TEXT NOT NULL DEFAULT 'idle' CHECK (status IN ('idle','running','succeeded','failed')),
  cursor TEXT,
  watermark TIMESTAMPTZ,
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  last_error TEXT,
  records_seen INTEGER NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(connection_id, object_type)
);

CREATE TABLE IF NOT EXISTS public.jobber_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  connection_id BIGINT NOT NULL REFERENCES public.jobber_connections(id) ON DELETE CASCADE,
  object_type TEXT NOT NULL CHECK (object_type IN ('clients','jobs','scheduled_items','quotes','invoices','payments')),
  external_id TEXT NOT NULL,
  related_client_id TEXT,
  parent_id TEXT,
  record_number TEXT,
  status TEXT,
  title TEXT,
  starts_at TIMESTAMPTZ,
  ends_at TIMESTAMPTZ,
  source_created_at TIMESTAMPTZ,
  source_updated_at TIMESTAMPTZ,
  direct_url TEXT,
  amount NUMERIC,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  content_hash TEXT NOT NULL,
  first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(connection_id, object_type, external_id)
);

CREATE INDEX IF NOT EXISTS jobber_records_org_type_idx
  ON public.jobber_records(organization_id, object_type);

ALTER TABLE public.jobber_sync_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jobber_records ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.jobber_sync_state FROM anon, authenticated;
REVOKE ALL ON public.jobber_records FROM anon, authenticated;

