-- Read-only financial-summary parity observations from legacy UI surfaces.
-- This table stores diagnostic values only and never feeds accounting reports.
BEGIN;

CREATE TABLE IF NOT EXISTS public.financial_summary_shadow_comparisons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  surface TEXT NOT NULL CHECK (surface IN ('home', 'reports')),
  period_start TIMESTAMPTZ NOT NULL,
  period_end TIMESTAMPTZ NOT NULL,
  legacy_values JSONB NOT NULL,
  canonical_values JSONB NOT NULL,
  legacy_sources JSONB NOT NULL DEFAULT '{}'::jsonb,
  canonical_sources JSONB NOT NULL DEFAULT '{}'::jsonb,
  differences JSONB NOT NULL DEFAULT '[]'::jsonb,
  classification TEXT NOT NULL CHECK (classification IN ('match', 'expected_source_difference', 'unexpected_mismatch')),
  calculation_version TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS financial_summary_shadow_org_created_idx
  ON public.financial_summary_shadow_comparisons (organization_id, created_at DESC);
CREATE INDEX IF NOT EXISTS financial_summary_shadow_classification_idx
  ON public.financial_summary_shadow_comparisons (classification, created_at DESC);

ALTER TABLE public.financial_summary_shadow_comparisons ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.financial_summary_shadow_comparisons FROM anon, authenticated;

COMMIT;
