-- QuickBooks read-only staging. No staged row is inserted into BookSmart's
-- transactions table; promotion requires a separate, user-approved workflow.
ALTER TABLE public.quickbooks_connections
  ADD COLUMN IF NOT EXISTS last_synced_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_sync_status TEXT
    CHECK (last_sync_status IS NULL OR last_sync_status IN ('running', 'completed', 'failed')),
  ADD COLUMN IF NOT EXISTS last_sync_error TEXT;

CREATE TABLE IF NOT EXISTS public.quickbooks_staged_entities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  entity_type TEXT NOT NULL CHECK (entity_type IN ('Account', 'Purchase', 'Bill', 'Invoice', 'Payment', 'Deposit')),
  external_id TEXT NOT NULL,
  display_name TEXT,
  transaction_date DATE,
  total_amount NUMERIC,
  payload JSONB NOT NULL,
  source_updated_at TIMESTAMPTZ,
  staged_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  import_status TEXT NOT NULL DEFAULT 'staged' CHECK (import_status IN ('staged', 'approved', 'rejected')),
  UNIQUE (organization_id, entity_type, external_id)
);

ALTER TABLE public.quickbooks_staged_entities ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.quickbooks_staged_entities FROM anon, authenticated;

CREATE INDEX IF NOT EXISTS quickbooks_staged_entities_org_type_idx
  ON public.quickbooks_staged_entities (organization_id, entity_type, transaction_date DESC);
