-- Phase 3: make CPA access an explicit, organization-scoped database invariant.
-- Apply through the Supabase migration workflow before deploying the matching app code.

BEGIN;

CREATE TABLE IF NOT EXISTS public.cpa_client_access (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cpa_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  client_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  order_id BIGINT REFERENCES public.orders(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'revoked')),
  consent_source TEXT NOT NULL DEFAULT 'client_order' CHECK (consent_source = 'client_order'),
  consent_granted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  revoked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (cpa_id, client_id, organization_id)
);

CREATE INDEX IF NOT EXISTS cpa_client_access_cpa_status_idx
  ON public.cpa_client_access (cpa_id, status);
CREATE INDEX IF NOT EXISTS cpa_client_access_client_status_idx
  ON public.cpa_client_access (client_id, status);
CREATE INDEX IF NOT EXISTS cpa_client_access_org_status_idx
  ON public.cpa_client_access (organization_id, status);

ALTER TABLE public.cpa_client_access ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.current_app_user_id()
RETURNS BIGINT
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
  SELECT id FROM public.users WHERE auth_id = auth.uid() LIMIT 1
$$;

CREATE OR REPLACE FUNCTION public.current_app_role()
RETURNS TEXT
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
  SELECT role FROM public.users WHERE auth_id = auth.uid() LIMIT 1
$$;

CREATE OR REPLACE FUNCTION public.is_approved_cpa()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.users
    WHERE auth_id = auth.uid()
      AND role = 'cpa'
      AND lower(coalesce(verification_status, '')) = 'approved'
  )
$$;

CREATE OR REPLACE FUNCTION public.cpa_has_client_access(target_client_id BIGINT)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
  SELECT public.is_approved_cpa() AND EXISTS (
    SELECT 1 FROM public.cpa_client_access
    WHERE cpa_id = public.current_app_user_id()
      AND client_id = target_client_id
      AND status = 'active'
  )
$$;

CREATE OR REPLACE FUNCTION public.cpa_has_org_access(target_org_id BIGINT)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
  SELECT public.is_approved_cpa() AND EXISTS (
    SELECT 1 FROM public.cpa_client_access
    WHERE cpa_id = public.current_app_user_id()
      AND organization_id = target_org_id
      AND status = 'active'
  )
$$;

CREATE OR REPLACE FUNCTION public.cpa_has_open_order_for_client(target_client_id BIGINT)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
  SELECT public.is_approved_cpa() AND EXISTS (
    SELECT 1 FROM public.orders
    WHERE cpa_id = public.current_app_user_id()
      AND user_id = target_client_id
      AND status IN ('pending', 'active', 'in_progress', 'in-progress')
  )
$$;

-- Prevent authenticated callers from self-approving, changing roles, relinking
-- auth identities, or modifying another user's profile. Service-role API writes
-- (including admin verification) remain permitted.
CREATE OR REPLACE FUNCTION public.protect_user_security_fields()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF auth.uid() IS NOT NULL AND coalesce(auth.role(), '') <> 'service_role' THEN
    IF OLD.auth_id IS NOT NULL AND OLD.auth_id IS DISTINCT FROM auth.uid() THEN
      RAISE EXCEPTION 'Users may only update their own profile';
    END IF;
    IF (NEW.auth_id IS DISTINCT FROM OLD.auth_id AND NOT (OLD.auth_id IS NULL AND NEW.auth_id = auth.uid()))
       OR NEW.role IS DISTINCT FROM OLD.role
       OR NEW.verification_status IS DISTINCT FROM OLD.verification_status THEN
      RAISE EXCEPTION 'Protected account fields cannot be changed directly';
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS protect_user_security_fields_trigger ON public.users;
CREATE TRIGGER protect_user_security_fields_trigger
  BEFORE UPDATE ON public.users
  FOR EACH ROW EXECUTE FUNCTION public.protect_user_security_fields();

CREATE OR REPLACE FUNCTION public.sync_cpa_access_from_order()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
BEGIN
  IF NEW.cpa_id IS NULL THEN
    RETURN NEW;
  END IF;

  IF NEW.status IN ('active', 'in_progress', 'in-progress') THEN
    INSERT INTO public.cpa_client_access (
      cpa_id, client_id, organization_id, order_id, status,
      consent_source, consent_granted_at, revoked_at, updated_at
    )
    SELECT NEW.cpa_id, NEW.user_id, organizations.id, NEW.id, 'active',
           'client_order', coalesce(NEW.created_at, now()), NULL, now()
    FROM public.organizations
    WHERE organizations.owner_id = NEW.user_id
    ON CONFLICT (cpa_id, client_id, organization_id) DO UPDATE SET
      order_id = EXCLUDED.order_id,
      status = 'active',
      consent_granted_at = EXCLUDED.consent_granted_at,
      revoked_at = NULL,
      updated_at = now();
  ELSE
    UPDATE public.cpa_client_access access
    SET status = 'revoked', revoked_at = now(), updated_at = now()
    WHERE access.cpa_id = NEW.cpa_id
      AND access.client_id = NEW.user_id
      AND access.status = 'active'
      AND NOT EXISTS (
        SELECT 1 FROM public.orders other_order
        WHERE other_order.cpa_id = NEW.cpa_id
          AND other_order.user_id = NEW.user_id
          AND other_order.id <> NEW.id
          AND other_order.status IN ('active', 'in_progress', 'in-progress')
      );
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS sync_cpa_access_from_order_trigger ON public.orders;
CREATE TRIGGER sync_cpa_access_from_order_trigger
  AFTER INSERT OR UPDATE OF status, cpa_id ON public.orders
  FOR EACH ROW EXECUTE FUNCTION public.sync_cpa_access_from_order();

CREATE OR REPLACE FUNCTION public.sync_cpa_access_for_new_organization()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
BEGIN
  INSERT INTO public.cpa_client_access (
    cpa_id, client_id, organization_id, order_id, status,
    consent_source, consent_granted_at, revoked_at, updated_at
  )
  SELECT orders.cpa_id, NEW.owner_id, NEW.id, max(orders.id), 'active',
         'client_order', min(orders.created_at), NULL, now()
  FROM public.orders
  WHERE orders.user_id = NEW.owner_id
    AND orders.cpa_id IS NOT NULL
    AND orders.status IN ('active', 'in_progress', 'in-progress')
  GROUP BY orders.cpa_id
  ON CONFLICT (cpa_id, client_id, organization_id) DO UPDATE SET
    status = 'active', revoked_at = NULL, updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS sync_cpa_access_for_new_organization_trigger ON public.organizations;
CREATE TRIGGER sync_cpa_access_for_new_organization_trigger
  AFTER INSERT ON public.organizations
  FOR EACH ROW EXECUTE FUNCTION public.sync_cpa_access_for_new_organization();

-- Backfill access for engagements that were already active before this migration.
INSERT INTO public.cpa_client_access (
  cpa_id, client_id, organization_id, order_id, status,
  consent_source, consent_granted_at
)
SELECT DISTINCT ON (orders.cpa_id, orders.user_id, organizations.id)
  orders.cpa_id, orders.user_id, organizations.id, orders.id, 'active',
  'client_order', coalesce(orders.created_at, now())
FROM public.orders
JOIN public.organizations ON organizations.owner_id = orders.user_id
WHERE orders.cpa_id IS NOT NULL
  AND orders.status IN ('active', 'in_progress', 'in-progress')
ORDER BY orders.cpa_id, orders.user_id, organizations.id, orders.created_at DESC
ON CONFLICT (cpa_id, client_id, organization_id) DO NOTHING;

-- RLS policies are OR-combined by PostgreSQL. Remove prior policies on the
-- protected tables so a legacy permissive policy cannot bypass this model.
DO $$
DECLARE
  policy_row RECORD;
BEGIN
  FOR policy_row IN
    SELECT schemaname, tablename, policyname
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename IN (
        'users', 'cpa_client_access', 'organizations', 'transactions',
        'orders', 'documents', 'user_documents', 'ai_strategies',
        'ai_tax_strategies', 'chats', 'messages'
      )
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON %I.%I', policy_row.policyname, policy_row.schemaname, policy_row.tablename);
  END LOOP;
END;
$$;

-- Users: own profile; admins; public-facing approved CPA profiles; and the
-- minimal client relationship needed by an approved CPA.
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Scoped user profile reads" ON public.users;
CREATE POLICY "Scoped user profile reads" ON public.users FOR SELECT TO authenticated
USING (
  auth_id = auth.uid()
  OR (auth_id IS NULL AND lower(email) = lower(coalesce(auth.jwt() ->> 'email', '')))
  OR public.current_app_role() = 'admin'
  OR (role = 'cpa' AND lower(coalesce(verification_status, '')) = 'approved')
  OR public.cpa_has_open_order_for_client(id)
  OR public.cpa_has_client_access(id)
  OR referred_by_cpa_id = public.current_app_user_id()
);
DROP POLICY IF EXISTS "Users create their own safe profile" ON public.users;
CREATE POLICY "Users create their own safe profile" ON public.users FOR INSERT TO authenticated
WITH CHECK (
  auth_id = auth.uid()
  AND role IN ('user', 'cpa')
  AND (
    (role = 'user' AND verification_status IS NULL)
    OR (role = 'cpa' AND lower(coalesce(verification_status, 'pending')) = 'pending')
  )
);
DROP POLICY IF EXISTS "Users update their own profile" ON public.users;
CREATE POLICY "Users update their own profile" ON public.users FOR UPDATE TO authenticated
USING (
  auth_id = auth.uid()
  OR (auth_id IS NULL AND lower(email) = lower(coalesce(auth.jwt() ->> 'email', '')))
)
WITH CHECK (auth_id = auth.uid());

ALTER TABLE public.cpa_client_access ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Participants view CPA access grants" ON public.cpa_client_access;
CREATE POLICY "Participants view CPA access grants" ON public.cpa_client_access FOR SELECT TO authenticated
USING (
  cpa_id = public.current_app_user_id()
  OR client_id = public.current_app_user_id()
  OR public.current_app_role() = 'admin'
);

ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Owners and engaged CPAs view organizations" ON public.organizations;
CREATE POLICY "Owners and engaged CPAs view organizations" ON public.organizations FOR SELECT TO authenticated
USING (owner_id = public.current_app_user_id() OR public.current_app_role() = 'admin' OR public.cpa_has_org_access(id));
DROP POLICY IF EXISTS "Owners manage organizations" ON public.organizations;
CREATE POLICY "Owners manage organizations" ON public.organizations FOR ALL TO authenticated
USING (owner_id = public.current_app_user_id()) WITH CHECK (owner_id = public.current_app_user_id());

ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Owners and engaged CPAs view transactions" ON public.transactions;
CREATE POLICY "Owners and engaged CPAs view transactions" ON public.transactions FOR SELECT TO authenticated
USING (
  public.current_app_role() = 'admin'
  OR public.cpa_has_org_access(org_id)
  OR EXISTS (SELECT 1 FROM public.organizations WHERE id = org_id AND owner_id = public.current_app_user_id())
);
DROP POLICY IF EXISTS "Owners manage transactions" ON public.transactions;
CREATE POLICY "Owners manage transactions" ON public.transactions FOR ALL TO authenticated
USING (EXISTS (SELECT 1 FROM public.organizations WHERE id = org_id AND owner_id = public.current_app_user_id()))
WITH CHECK (EXISTS (SELECT 1 FROM public.organizations WHERE id = org_id AND owner_id = public.current_app_user_id()));

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Order participants view orders" ON public.orders;
CREATE POLICY "Order participants view orders" ON public.orders FOR SELECT TO authenticated
USING (
  user_id = public.current_app_user_id()
  OR public.current_app_role() = 'admin'
  OR (cpa_id = public.current_app_user_id() AND public.is_approved_cpa())
);
DROP POLICY IF EXISTS "Clients create their own orders" ON public.orders;
CREATE POLICY "Clients create their own orders" ON public.orders FOR INSERT TO authenticated
WITH CHECK (user_id = public.current_app_user_id());

ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Owners and engaged CPAs view documents" ON public.documents;
CREATE POLICY "Owners and engaged CPAs view documents" ON public.documents FOR SELECT TO authenticated
USING (
  user_id = public.current_app_user_id()
  OR public.current_app_role() = 'admin'
  OR public.cpa_has_client_access(user_id)
  OR public.cpa_has_org_access(org_id)
);
DROP POLICY IF EXISTS "Owners manage documents" ON public.documents;
CREATE POLICY "Owners manage documents" ON public.documents FOR ALL TO authenticated
USING (user_id = public.current_app_user_id()) WITH CHECK (user_id = public.current_app_user_id());

ALTER TABLE public.user_documents ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Owners and engaged CPAs view user documents" ON public.user_documents;
CREATE POLICY "Owners and engaged CPAs view user documents" ON public.user_documents FOR SELECT TO authenticated
USING (
  user_id = public.current_app_user_id()
  OR public.current_app_role() = 'admin'
  OR public.cpa_has_client_access(user_id)
);
DROP POLICY IF EXISTS "Owners manage user documents" ON public.user_documents;
CREATE POLICY "Owners manage user documents" ON public.user_documents FOR ALL TO authenticated
USING (user_id = public.current_app_user_id()) WITH CHECK (user_id = public.current_app_user_id());

ALTER TABLE public.ai_strategies ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Owners and engaged CPAs view AI strategies" ON public.ai_strategies;
CREATE POLICY "Owners and engaged CPAs view AI strategies" ON public.ai_strategies FOR SELECT TO authenticated
USING (
  user_id = public.current_app_user_id()
  OR public.current_app_role() = 'admin'
  OR public.cpa_has_client_access(user_id)
);
DROP POLICY IF EXISTS "Owners manage AI strategies" ON public.ai_strategies;
CREATE POLICY "Owners manage AI strategies" ON public.ai_strategies FOR ALL TO authenticated
USING (user_id = public.current_app_user_id()) WITH CHECK (user_id = public.current_app_user_id());

ALTER TABLE public.ai_tax_strategies ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Owners and engaged CPAs view tax strategies" ON public.ai_tax_strategies;
CREATE POLICY "Owners and engaged CPAs view tax strategies" ON public.ai_tax_strategies FOR SELECT TO authenticated
USING (
  user_id = public.current_app_user_id()
  OR public.current_app_role() = 'admin'
  OR public.cpa_has_client_access(user_id)
  OR public.cpa_has_org_access(org_id)
);
DROP POLICY IF EXISTS "Owners manage tax strategies" ON public.ai_tax_strategies;
CREATE POLICY "Owners manage tax strategies" ON public.ai_tax_strategies FOR ALL TO authenticated
USING (user_id = public.current_app_user_id()) WITH CHECK (user_id = public.current_app_user_id());

ALTER TABLE public.chats ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Chat participants view chats" ON public.chats FOR SELECT TO authenticated
USING (
  sender_id = public.current_app_user_id()
  OR receiver_id = public.current_app_user_id()
  OR public.current_app_role() = 'admin'
);
CREATE POLICY "Users create chats they participate in" ON public.chats FOR INSERT TO authenticated
WITH CHECK (sender_id = public.current_app_user_id() OR receiver_id = public.current_app_user_id());
CREATE POLICY "Chat participants update chats" ON public.chats FOR UPDATE TO authenticated
USING (sender_id = public.current_app_user_id() OR receiver_id = public.current_app_user_id())
WITH CHECK (sender_id = public.current_app_user_id() OR receiver_id = public.current_app_user_id());

ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Chat participants view messages" ON public.messages FOR SELECT TO authenticated
USING (
  public.current_app_role() = 'admin'
  OR EXISTS (
    SELECT 1 FROM public.chats
    WHERE chats.id = messages.chat_id
      AND (chats.sender_id = public.current_app_user_id() OR chats.receiver_id = public.current_app_user_id())
  )
);
CREATE POLICY "Chat participants send messages" ON public.messages FOR INSERT TO authenticated
WITH CHECK (
  sender_id = public.current_app_user_id()
  AND EXISTS (
    SELECT 1 FROM public.chats
    WHERE chats.id = messages.chat_id
      AND (chats.sender_id = public.current_app_user_id() OR chats.receiver_id = public.current_app_user_id())
  )
);
CREATE POLICY "Recipients update message state" ON public.messages FOR UPDATE TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.chats
    WHERE chats.id = messages.chat_id
      AND (chats.sender_id = public.current_app_user_id() OR chats.receiver_id = public.current_app_user_id())
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.chats
    WHERE chats.id = messages.chat_id
      AND (chats.sender_id = public.current_app_user_id() OR chats.receiver_id = public.current_app_user_id())
  )
);

COMMIT;
