-- Manual, read-only Gmail receipt evidence foundation. Gmail data never creates
-- or modifies an accounting transaction.
BEGIN;
CREATE TABLE IF NOT EXISTS public.gmail_connections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL UNIQUE REFERENCES public.organizations(id) ON DELETE CASCADE,
  connected_by_user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
  google_account_email TEXT,
  access_token_encrypted TEXT,
  refresh_token_encrypted TEXT,
  access_token_expires_at TIMESTAMPTZ,
  granted_scopes TEXT[] NOT NULL DEFAULT ARRAY['https://www.googleapis.com/auth/gmail.readonly']::TEXT[],
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','disconnected','error','reauth_required')),
  last_scan_at TIMESTAMPTZ,
  last_scan_status TEXT CHECK (last_scan_status IS NULL OR last_scan_status IN ('running','completed','partial','failed')),
  last_scan_error TEXT,
  connected_at TIMESTAMPTZ NOT NULL DEFAULT now(), disconnected_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.gmail_oauth_states (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  state_hash TEXT NOT NULL UNIQUE,
  organization_id BIGINT NOT NULL UNIQUE REFERENCES public.organizations(id) ON DELETE CASCADE,
  auth_user_id UUID NOT NULL, expires_at TIMESTAMPTZ NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS gmail_oauth_states_expiry_idx ON public.gmail_oauth_states(expires_at);
ALTER TABLE public.gmail_connections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gmail_oauth_states ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.gmail_connections FROM anon, authenticated;
REVOKE ALL ON public.gmail_oauth_states FROM anon, authenticated;
COMMIT;
