-- Contractor financial intelligence matching and configuration foundation.
-- Additive only: these records explain and project trusted source data. They
-- never create, classify, approve, or alter accounting transactions.
BEGIN;

CREATE TABLE IF NOT EXISTS public.contractor_financial_settings (
  organization_id BIGINT PRIMARY KEY REFERENCES public.organizations(id) ON DELETE CASCADE,
  target_gross_margin NUMERIC CHECK (target_gross_margin IS NULL OR (target_gross_margin >= 0 AND target_gross_margin <= 1)),
  target_margin_source TEXT CHECK (target_margin_source IS NULL OR target_margin_source IN ('organization','industry')),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.contractor_financial_matches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  source_provider TEXT NOT NULL CHECK (source_provider IN ('booksmart','quickbooks','plaid','receipt','gmail')),
  source_record_type TEXT NOT NULL,
  source_record_id TEXT NOT NULL,
  jobber_job_id TEXT,
  confidence TEXT NOT NULL CHECK (confidence IN ('confirmed','high','medium','low','unmatched')),
  score NUMERIC NOT NULL DEFAULT 0 CHECK (score >= 0),
  match_reasons JSONB NOT NULL DEFAULT '[]'::jsonb,
  source_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
  requires_confirmation BOOLEAN NOT NULL DEFAULT false,
  status TEXT NOT NULL DEFAULT 'suggested' CHECK (status IN ('suggested','confirmed','rejected','unmatched')),
  calculation_version TEXT NOT NULL,
  confirmed_by BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
  confirmed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (organization_id, source_provider, source_record_type, source_record_id)
);

CREATE TABLE IF NOT EXISTS public.contractor_job_cost_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  match_id BIGINT REFERENCES public.contractor_financial_matches(id) ON DELETE SET NULL,
  jobber_job_id TEXT NOT NULL,
  source_provider TEXT NOT NULL CHECK (source_provider IN ('booksmart','quickbooks','plaid')),
  source_record_type TEXT NOT NULL,
  source_record_id TEXT NOT NULL,
  amount NUMERIC NOT NULL CHECK (amount >= 0),
  cost_category TEXT,
  confidence TEXT NOT NULL CHECK (confidence IN ('confirmed','high')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (organization_id, source_provider, source_record_type, source_record_id)
);

CREATE TABLE IF NOT EXISTS public.contractor_receipt_extractions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  -- user_documents.id is not a standalone unique key in every deployed
  -- BookSmart schema. Ownership is verified by the server before this
  -- provenance ID is stored, so do not impose an incompatible foreign key.
  document_id BIGINT,
  source_id TEXT NOT NULL,
  vendor TEXT,
  receipt_date DATE,
  subtotal NUMERIC CHECK (subtotal IS NULL OR subtotal >= 0),
  tax NUMERIC CHECK (tax IS NULL OR tax >= 0),
  total NUMERIC CHECK (total IS NULL OR total >= 0),
  payment_method TEXT,
  payment_last_four TEXT CHECK (payment_last_four IS NULL OR payment_last_four ~ '^[0-9]{4}$'),
  po_number TEXT,
  job_number TEXT,
  customer_or_project TEXT,
  receipt_number TEXT,
  line_items JSONB NOT NULL DEFAULT '[]'::jsonb,
  warnings JSONB NOT NULL DEFAULT '[]'::jsonb,
  schema_version TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (organization_id, source_id)
);

CREATE TABLE IF NOT EXISTS public.contractor_source_links (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  left_provider TEXT NOT NULL,
  left_record_type TEXT NOT NULL,
  left_record_id TEXT NOT NULL,
  right_provider TEXT NOT NULL,
  right_record_type TEXT NOT NULL,
  right_record_id TEXT NOT NULL,
  confidence TEXT NOT NULL CHECK (confidence IN ('high','medium','low','unmatched')),
  score NUMERIC NOT NULL DEFAULT 0 CHECK (score >= 0),
  match_reasons JSONB NOT NULL DEFAULT '[]'::jsonb,
  requires_confirmation BOOLEAN NOT NULL DEFAULT false,
  status TEXT NOT NULL DEFAULT 'suggested' CHECK (status IN ('suggested','confirmed','rejected','unmatched')),
  calculation_version TEXT NOT NULL,
  confirmed_by BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
  confirmed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (organization_id, left_provider, left_record_type, left_record_id, right_provider, right_record_type, right_record_id)
);

CREATE INDEX IF NOT EXISTS contractor_matches_org_job_idx
  ON public.contractor_financial_matches (organization_id, jobber_job_id, confidence);
CREATE INDEX IF NOT EXISTS contractor_costs_org_job_idx
  ON public.contractor_job_cost_assignments (organization_id, jobber_job_id);

ALTER TABLE public.contractor_financial_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contractor_financial_matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contractor_job_cost_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contractor_receipt_extractions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contractor_source_links ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.contractor_financial_settings FROM anon, authenticated;
REVOKE ALL ON public.contractor_financial_matches FROM anon, authenticated;
REVOKE ALL ON public.contractor_job_cost_assignments FROM anon, authenticated;
REVOKE ALL ON public.contractor_receipt_extractions FROM anon, authenticated;
REVOKE ALL ON public.contractor_source_links FROM anon, authenticated;

CREATE OR REPLACE FUNCTION public.confirm_contractor_receipt_job_cost(
  requested_organization_id BIGINT,
  requested_auth_user_id UUID,
  requested_receipt_source_id TEXT,
  requested_transaction_id BIGINT,
  requested_jobber_job_id TEXT
)
RETURNS TABLE(assignment_id BIGINT, assigned_amount NUMERIC, source_provider TEXT)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
#variable_conflict use_column
DECLARE
  owner_user_id BIGINT;
  transaction_row public.transactions%ROWTYPE;
  provider TEXT;
  confirmed_match_id BIGINT;
  new_assignment_id BIGINT;
BEGIN
  SELECT u.id INTO owner_user_id
    FROM public.organizations o JOIN public.users u ON u.id = o.owner_id
   WHERE o.id = requested_organization_id AND u.auth_id = requested_auth_user_id;
  IF owner_user_id IS NULL THEN RAISE EXCEPTION 'Organization not found'; END IF;

  IF NOT EXISTS (SELECT 1 FROM public.contractor_receipt_extractions r WHERE r.organization_id = requested_organization_id AND r.source_id = requested_receipt_source_id) THEN
    RAISE EXCEPTION 'Receipt extraction not found';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.jobber_records j WHERE j.organization_id = requested_organization_id AND j.object_type = 'jobs' AND j.external_id = requested_jobber_job_id AND j.is_archived = false) THEN
    RAISE EXCEPTION 'Jobber job not found';
  END IF;
  SELECT * INTO transaction_row FROM public.transactions t
   WHERE t.id = requested_transaction_id AND t.org_id = requested_organization_id;
  IF transaction_row.id IS NULL THEN RAISE EXCEPTION 'Transaction not found'; END IF;
  IF transaction_row.pending IS TRUE THEN RAISE EXCEPTION 'Pending transactions cannot be assigned'; END IF;
  IF transaction_row.amount >= 0 THEN RAISE EXCEPTION 'Only expense transactions can be assigned'; END IF;
  provider := CASE WHEN transaction_row.quickbooks_external_id IS NOT NULL THEN 'quickbooks'
                   WHEN transaction_row.plaid_transaction_id IS NOT NULL THEN 'plaid' ELSE 'booksmart' END;

  INSERT INTO public.contractor_financial_matches (
    organization_id, source_provider, source_record_type, source_record_id, jobber_job_id,
    confidence, score, match_reasons, source_ids, requires_confirmation, status,
    calculation_version, confirmed_by, confirmed_at, updated_at
  ) VALUES (
    requested_organization_id, 'receipt', 'contractor_receipt_extraction', requested_receipt_source_id, requested_jobber_job_id,
    'confirmed', 100, '["owner_confirmed"]'::jsonb,
    jsonb_build_array(requested_receipt_source_id, requested_jobber_job_id), false, 'confirmed',
    'contractor-job-match-v1', owner_user_id, now(), now()
  ) ON CONFLICT (organization_id, source_provider, source_record_type, source_record_id)
  DO UPDATE SET jobber_job_id = EXCLUDED.jobber_job_id, confidence = 'confirmed', score = 100,
    match_reasons = EXCLUDED.match_reasons, source_ids = EXCLUDED.source_ids, requires_confirmation = false,
    status = 'confirmed', confirmed_by = owner_user_id, confirmed_at = now(), updated_at = now()
  RETURNING id INTO confirmed_match_id;

  INSERT INTO public.contractor_source_links (
    organization_id, left_provider, left_record_type, left_record_id, right_provider,
    right_record_type, right_record_id, confidence, score, match_reasons,
    requires_confirmation, status, calculation_version, confirmed_by, confirmed_at, updated_at
  ) VALUES (
    requested_organization_id, 'receipt', 'contractor_receipt_extraction', requested_receipt_source_id, provider,
    'transaction', requested_transaction_id::text, 'high', 100, '["owner_confirmed"]'::jsonb,
    false, 'confirmed', 'receipt-transaction-match-v1', owner_user_id, now(), now()
  ) ON CONFLICT (organization_id, left_provider, left_record_type, left_record_id, right_provider, right_record_type, right_record_id)
  DO UPDATE SET confidence = 'high', score = 100, match_reasons = EXCLUDED.match_reasons,
    requires_confirmation = false, status = 'confirmed', confirmed_by = owner_user_id,
    confirmed_at = now(), updated_at = now();

  INSERT INTO public.contractor_job_cost_assignments (
    organization_id, match_id, jobber_job_id, source_provider, source_record_type,
    source_record_id, amount, confidence
  ) VALUES (
    requested_organization_id, confirmed_match_id, requested_jobber_job_id, provider, 'transaction',
    requested_transaction_id::text, abs(transaction_row.amount), 'confirmed'
  ) ON CONFLICT (organization_id, source_provider, source_record_type, source_record_id)
  DO UPDATE SET match_id = EXCLUDED.match_id, jobber_job_id = EXCLUDED.jobber_job_id,
    amount = EXCLUDED.amount, confidence = 'confirmed'
  RETURNING id INTO new_assignment_id;

  RETURN QUERY SELECT new_assignment_id, abs(transaction_row.amount), provider;
END;
$$;

REVOKE ALL ON FUNCTION public.confirm_contractor_receipt_job_cost(BIGINT, UUID, TEXT, BIGINT, TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.confirm_contractor_receipt_job_cost(BIGINT, UUID, TEXT, BIGINT, TEXT) TO service_role;

COMMIT;
