-- Auditable execution records for manual and scheduled monitoring.
-- Additive only: no accounting, integration, document, or CPA tables change.

BEGIN;

CREATE TABLE IF NOT EXISTS public.monitoring_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT REFERENCES public.organizations(id) ON DELETE CASCADE,
  trigger_type TEXT NOT NULL CHECK (trigger_type IN ('manual', 'scheduled')),
  status TEXT NOT NULL DEFAULT 'running' CHECK (status IN ('running', 'completed', 'partial', 'failed')),
  calculation_version TEXT NOT NULL DEFAULT 'financial-summary-v1',
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ,
  organizations_evaluated INTEGER NOT NULL DEFAULT 0,
  signals_created INTEGER NOT NULL DEFAULT 0,
  signals_updated INTEGER NOT NULL DEFAULT 0,
  signals_resolved INTEGER NOT NULL DEFAULT 0,
  tasks_created INTEGER NOT NULL DEFAULT 0,
  error_count INTEGER NOT NULL DEFAULT 0,
  errors JSONB NOT NULL DEFAULT '[]'::jsonb,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb
);

ALTER TABLE public.business_signals
  ADD COLUMN IF NOT EXISTS last_seen_run_id BIGINT
    REFERENCES public.monitoring_runs(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS monitoring_runs_started_idx
  ON public.monitoring_runs (started_at DESC);
CREATE INDEX IF NOT EXISTS monitoring_runs_org_started_idx
  ON public.monitoring_runs (organization_id, started_at DESC);

ALTER TABLE public.monitoring_runs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.monitoring_runs FROM anon, authenticated;

COMMIT;
