-- Phase 1 Jobber integration: secure, read-only OAuth connection foundation.
-- Configure only read scopes in Jobber Developer Center. This migration does
-- not create imported-data, transaction, financial, or monitoring tables.

CREATE TABLE IF NOT EXISTS public.jobber_connections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL UNIQUE REFERENCES public.organizations(id) ON DELETE CASCADE,
  jobber_account_id TEXT NOT NULL UNIQUE,
  jobber_account_name TEXT,
  access_token_encrypted TEXT,
  refresh_token_encrypted TEXT,
  access_token_expires_at TIMESTAMPTZ,
  token_type TEXT NOT NULL DEFAULT 'Bearer' CHECK (token_type = 'Bearer'),
  access_mode TEXT NOT NULL DEFAULT 'read_only' CHECK (access_mode = 'read_only'),
  granted_scopes TEXT[] NOT NULL DEFAULT ARRAY[
    'Clients: read only',
    'Quotes: read only',
    'Jobs: read only',
    'Scheduled Items: read only',
    'Invoices: read only',
    'Jobber Payments: read only'
  ]::TEXT[],
  api_version TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disconnected', 'error')),
  verified_at TIMESTAMPTZ,
  last_successful_sync_at TIMESTAMPTZ,
  last_sync_error TEXT,
  connected_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  disconnected_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.jobber_connections ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.jobber_connections FROM anon, authenticated;

CREATE TABLE IF NOT EXISTS public.jobber_oauth_states (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  state_hash TEXT NOT NULL UNIQUE,
  organization_id BIGINT NOT NULL UNIQUE REFERENCES public.organizations(id) ON DELETE CASCADE,
  auth_user_id UUID NOT NULL,
  pkce_verifier_encrypted TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.jobber_oauth_states ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.jobber_oauth_states FROM anon, authenticated;

CREATE INDEX IF NOT EXISTS jobber_oauth_states_expires_at_idx
  ON public.jobber_oauth_states(expires_at);
