-- Scheduled monitoring execution safety and notification-ready events.
-- Additive only. This migration does not send notifications or modify any
-- accounting, transaction, document, integration, or CPA-access records.

BEGIN;

ALTER TABLE public.monitoring_runs
  ADD COLUMN IF NOT EXISTS idempotency_key TEXT,
  ADD COLUMN IF NOT EXISTS notification_events_created INTEGER NOT NULL DEFAULT 0;

CREATE UNIQUE INDEX IF NOT EXISTS monitoring_runs_idempotency_key_idx
  ON public.monitoring_runs (idempotency_key)
  WHERE idempotency_key IS NOT NULL;

-- Only one scheduled evaluator may be active globally. Manual organization
-- runs remain available for controlled testing and support.
CREATE UNIQUE INDEX IF NOT EXISTS monitoring_runs_single_scheduled_run_idx
  ON public.monitoring_runs ((1))
  WHERE trigger_type = 'scheduled' AND status = 'running';

CREATE TABLE IF NOT EXISTS public.monitoring_notification_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  run_id BIGINT NOT NULL REFERENCES public.monitoring_runs(id) ON DELETE CASCADE,
  signal_id BIGINT REFERENCES public.business_signals(id) ON DELETE CASCADE,
  task_id BIGINT REFERENCES public.financial_tasks(id) ON DELETE CASCADE,
  event_key TEXT NOT NULL UNIQUE,
  event_type TEXT NOT NULL CHECK (event_type IN ('signal_created', 'task_created', 'connection_recovered')),
  channel TEXT NOT NULL DEFAULT 'in_app' CHECK (channel IN ('in_app', 'email', 'sms', 'push')),
  delivery_status TEXT NOT NULL DEFAULT 'suppressed'
    CHECK (delivery_status IN ('pending', 'suppressed', 'sent', 'failed')),
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  available_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  delivered_at TIMESTAMPTZ,
  attempt_count INTEGER NOT NULL DEFAULT 0,
  last_error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS monitoring_notification_events_delivery_idx
  ON public.monitoring_notification_events (delivery_status, available_at)
  WHERE delivery_status IN ('pending', 'failed');
CREATE INDEX IF NOT EXISTS monitoring_notification_events_org_created_idx
  ON public.monitoring_notification_events (organization_id, created_at DESC);

ALTER TABLE public.monitoring_notification_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.monitoring_notification_events FROM anon, authenticated;

COMMIT;
