-- P3 foundations: industry configuration and verified provider balance history.
-- These tables are server-managed configuration/snapshots. They do not alter
-- canonical transactions or generate unsupported industry KPIs.

BEGIN;

ALTER TABLE public.business_industry_profiles
  ADD COLUMN IF NOT EXISTS thresholds JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS prioritized_insights JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS future_kpis JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS recommended_integrations JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS onboarding_questions JSONB NOT NULL DEFAULT '[]'::jsonb;

CREATE TABLE IF NOT EXISTS public.industry_profile_definitions (
  profile_key TEXT PRIMARY KEY,
  display_name TEXT NOT NULL,
  terminology JSONB NOT NULL DEFAULT '{}'::jsonb,
  enabled_rule_groups JSONB NOT NULL DEFAULT '[]'::jsonb,
  thresholds JSONB NOT NULL DEFAULT '{}'::jsonb,
  prioritized_insights JSONB NOT NULL DEFAULT '[]'::jsonb,
  future_kpis JSONB NOT NULL DEFAULT '[]'::jsonb,
  recommended_integrations JSONB NOT NULL DEFAULT '[]'::jsonb,
  onboarding_questions JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO public.industry_profile_definitions
  (profile_key, display_name, terminology, enabled_rule_groups, future_kpis)
VALUES
  ('generic_small_business', 'Small Business', '{}', '["core_financial","bookkeeping","connections"]', '[]'),
  ('construction', 'Construction', '{"customer":"client","project":"job"}', '["core_financial","bookkeeping","connections"]', '["job_margin","material_cost","subcontractor_cost","receivables","project_cash_flow"]'),
  ('real_estate_agent', 'Real Estate Agent', '{"revenue":"commissions","customer":"client"}', '["core_financial","bookkeeping","connections"]', '["commission_pipeline","marketing_roi","closing_cash_flow"]'),
  ('gig_driver', 'Gig Driver', '{"revenue":"platform earnings"}', '["core_financial","bookkeeping","connections"]', '["earnings_per_mile","vehicle_cost_per_mile","platform_mix"]'),
  ('real_estate_investor', 'Real Estate Investor', '{"project":"property","revenue":"rental income"}', '["core_financial","bookkeeping","connections"]', '["property_cash_flow","occupancy","debt_service_coverage"]'),
  ('professional_services', 'Professional Services', '{"customer":"client","project":"engagement"}', '["core_financial","bookkeeping","connections"]', '["utilization","client_margin","receivables_days"]')
ON CONFLICT (profile_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  terminology = EXCLUDED.terminology,
  enabled_rule_groups = EXCLUDED.enabled_rule_groups,
  future_kpis = EXCLUDED.future_kpis,
  updated_at = now();

ALTER TABLE public.business_industry_profiles
  DROP CONSTRAINT IF EXISTS business_industry_profiles_profile_key_fkey;
UPDATE public.business_industry_profiles profile
SET profile_key = 'generic_small_business'
WHERE NOT EXISTS (
  SELECT 1 FROM public.industry_profile_definitions definition
  WHERE definition.profile_key = profile.profile_key
);
ALTER TABLE public.business_industry_profiles
  ADD CONSTRAINT business_industry_profiles_profile_key_fkey
  FOREIGN KEY (profile_key) REFERENCES public.industry_profile_definitions(profile_key);

CREATE TABLE IF NOT EXISTS public.account_balance_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  provider TEXT NOT NULL CHECK (provider IN ('plaid')),
  external_account_id TEXT NOT NULL,
  account_name TEXT NOT NULL,
  account_type TEXT,
  account_subtype TEXT,
  current_balance NUMERIC,
  available_balance NUMERIC,
  credit_limit NUMERIC,
  currency TEXT NOT NULL DEFAULT 'USD',
  balance_timestamp TIMESTAMPTZ NOT NULL,
  fetched_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  UNIQUE (organization_id, provider, external_account_id, balance_timestamp)
);

CREATE INDEX IF NOT EXISTS account_balance_snapshots_latest_idx
  ON public.account_balance_snapshots (organization_id, external_account_id, balance_timestamp DESC);

ALTER TABLE public.industry_profile_definitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.account_balance_snapshots ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.industry_profile_definitions FROM anon, authenticated;
REVOKE ALL ON public.account_balance_snapshots FROM anon, authenticated;

COMMIT;
