-- Additive QuickBooks chart-of-accounts mappings. Accounts remain reference
-- records and never become BookSmart transactions.
CREATE TABLE IF NOT EXISTS public.quickbooks_account_mappings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  quickbooks_account_id TEXT NOT NULL,
  quickbooks_account_name TEXT NOT NULL,
  quickbooks_account_type TEXT,
  mapping_kind TEXT NOT NULL CHECK (mapping_kind IN ('category', 'role', 'ignored')),
  category_id INTEGER,
  sub_category_id INTEGER,
  account_role TEXT CHECK (account_role IS NULL OR account_role IN (
    'bank', 'credit_card', 'loan', 'accounts_receivable', 'accounts_payable', 'equity'
  )),
  created_by UUID NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (organization_id, quickbooks_account_id),
  CHECK (
    (mapping_kind = 'category' AND category_id IS NOT NULL AND account_role IS NULL) OR
    (mapping_kind = 'role' AND account_role IS NOT NULL AND category_id IS NULL AND sub_category_id IS NULL) OR
    (mapping_kind = 'ignored' AND category_id IS NULL AND sub_category_id IS NULL AND account_role IS NULL)
  )
);

CREATE TABLE IF NOT EXISTS public.quickbooks_account_mapping_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  quickbooks_account_id TEXT NOT NULL,
  previous_mapping JSONB,
  new_mapping JSONB NOT NULL,
  changed_by UUID NOT NULL,
  changed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.quickbooks_account_mappings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quickbooks_account_mapping_history ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.quickbooks_account_mappings FROM anon, authenticated;
REVOKE ALL ON public.quickbooks_account_mapping_history FROM anon, authenticated;

CREATE INDEX IF NOT EXISTS quickbooks_account_mappings_org_idx
  ON public.quickbooks_account_mappings (organization_id, mapping_kind);

-- Apply a confirmed category mapping only while a new QuickBooks transaction is
-- inserted. Existing transactions and non-QuickBooks imports are never touched.
CREATE OR REPLACE FUNCTION public.apply_quickbooks_account_mapping()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  source_account_id TEXT;
  mapped_category_id INTEGER;
  mapped_sub_category_id INTEGER;
BEGIN
  IF NEW.quickbooks_entity_type IS NULL OR NEW.quickbooks_external_id IS NULL THEN
    RETURN NEW;
  END IF;

  SELECT COALESCE(
    line #>> '{AccountBasedExpenseLineDetail,AccountRef,value}',
    line #>> '{ItemBasedExpenseLineDetail,ItemAccountRef,value}',
    line #>> '{DepositLineDetail,AccountRef,value}',
    line #>> '{SalesItemLineDetail,ItemAccountRef,value}'
  )
  INTO source_account_id
  FROM public.quickbooks_staged_entities q
  CROSS JOIN LATERAL jsonb_array_elements(COALESCE(q.payload->'Line', '[]'::jsonb)) line
  WHERE q.organization_id = NEW.org_id
    AND q.entity_type = NEW.quickbooks_entity_type
    AND q.external_id = NEW.quickbooks_external_id
    AND COALESCE(
      line #>> '{AccountBasedExpenseLineDetail,AccountRef,value}',
      line #>> '{ItemBasedExpenseLineDetail,ItemAccountRef,value}',
      line #>> '{DepositLineDetail,AccountRef,value}',
      line #>> '{SalesItemLineDetail,ItemAccountRef,value}'
    ) IS NOT NULL
  LIMIT 1;

  IF source_account_id IS NULL THEN RETURN NEW; END IF;

  SELECT m.category_id, m.sub_category_id
    INTO mapped_category_id, mapped_sub_category_id
    FROM public.quickbooks_account_mappings m
   WHERE m.organization_id = NEW.org_id
     AND m.quickbooks_account_id = source_account_id
     AND m.mapping_kind = 'category';

  IF mapped_category_id IS NOT NULL THEN
    NEW.category_id := mapped_category_id;
    NEW.sub_category_id := mapped_sub_category_id;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS apply_quickbooks_account_mapping_on_insert ON public.transactions;
CREATE TRIGGER apply_quickbooks_account_mapping_on_insert
BEFORE INSERT ON public.transactions
FOR EACH ROW EXECUTE FUNCTION public.apply_quickbooks_account_mapping();
