-- BookSmart year-round monitoring foundation.
--
-- This migration is intentionally additive. It does not alter transactions,
-- financial statements, documents, Plaid, QuickBooks, or CPA access. Signals
-- and tasks are server-managed projections of the existing accounting source
-- of truth and must not become a second bookkeeping ledger.

BEGIN;

CREATE TABLE IF NOT EXISTS public.business_industry_profiles (
  organization_id BIGINT PRIMARY KEY
    REFERENCES public.organizations(id) ON DELETE CASCADE,
  profile_key TEXT NOT NULL DEFAULT 'generic_small_business',
  terminology JSONB NOT NULL DEFAULT '{}'::jsonb,
  enabled_rule_groups JSONB NOT NULL DEFAULT '[]'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.business_signals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL
    REFERENCES public.organizations(id) ON DELETE CASCADE,
  signal_key TEXT NOT NULL,
  signal_type TEXT NOT NULL,
  category TEXT NOT NULL,
  severity TEXT NOT NULL
    CHECK (severity IN ('info', 'positive', 'low', 'medium', 'high', 'critical')),
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  amount NUMERIC,
  percentage NUMERIC,
  status TEXT NOT NULL DEFAULT 'open'
    CHECK (status IN ('open', 'resolved', 'dismissed')),
  recommended_action TEXT,
  cta_label TEXT,
  cta_route TEXT,
  requires_cpa_review BOOLEAN NOT NULL DEFAULT false,
  cpa_review_level TEXT NOT NULL DEFAULT 'none'
    CHECK (cpa_review_level IN ('none', 'optional', 'recommended', 'urgent')),
  detected_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  resolved_at TIMESTAMPTZ,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  UNIQUE (organization_id, signal_key, status)
);

CREATE TABLE IF NOT EXISTS public.financial_tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL
    REFERENCES public.organizations(id) ON DELETE CASCADE,
  source TEXT NOT NULL
    CHECK (source IN ('signal', 'bookkeeping', 'tax_calendar')),
  source_id TEXT,
  category TEXT NOT NULL,
  priority TEXT NOT NULL
    CHECK (priority IN ('low', 'medium', 'high', 'critical')),
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  due_date DATE,
  status TEXT NOT NULL DEFAULT 'open'
    CHECK (status IN ('open', 'in_progress', 'waiting', 'completed', 'dismissed')),
  cta_label TEXT,
  cta_route TEXT,
  requires_cpa BOOLEAN NOT NULL DEFAULT false,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Read/query indexes for organization-scoped monitoring views.
CREATE INDEX IF NOT EXISTS business_signals_org_status_idx
  ON public.business_signals (organization_id, status, severity);

CREATE INDEX IF NOT EXISTS business_signals_detected_at_idx
  ON public.business_signals (organization_id, detected_at DESC);

CREATE INDEX IF NOT EXISTS financial_tasks_org_status_idx
  ON public.financial_tasks (organization_id, status, due_date);

-- Prevent a monitoring run from creating duplicate active work for the same
-- source. A completed or dismissed task may be recreated by a later event.
CREATE UNIQUE INDEX IF NOT EXISTS financial_tasks_active_source_key
  ON public.financial_tasks (organization_id, source, source_id)
  WHERE source_id IS NOT NULL
    AND status IN ('open', 'in_progress', 'waiting');

ALTER TABLE public.business_industry_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.business_signals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.financial_tasks ENABLE ROW LEVEL SECURITY;

-- Monitoring writes remain server-side until explicit owner/CPA policies and
-- mutation endpoints are reviewed. The service role is not affected.
REVOKE ALL ON public.business_industry_profiles FROM anon, authenticated;
REVOKE ALL ON public.business_signals FROM anon, authenticated;
REVOKE ALL ON public.financial_tasks FROM anon, authenticated;

COMMIT;
