-- Additive lifecycle support for BookSmart monitoring.
-- Safe to run after 20260809_business_monitoring.sql. This migration does not
-- modify accounting transactions, reports, documents, bank data, or CPA access.

BEGIN;

ALTER TABLE public.business_signals
  ADD COLUMN IF NOT EXISTS current_value NUMERIC,
  ADD COLUMN IF NOT EXISTS comparison_value NUMERIC,
  ADD COLUMN IF NOT EXISTS calculation_version TEXT NOT NULL DEFAULT 'financial-summary-v1',
  ADD COLUMN IF NOT EXISTS confidence NUMERIC,
  ADD COLUMN IF NOT EXISTS dismissed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER TABLE public.business_signals
  DROP CONSTRAINT IF EXISTS business_signals_confidence_check;
ALTER TABLE public.business_signals
  ADD CONSTRAINT business_signals_confidence_check
  CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1));

ALTER TABLE public.business_signals
  DROP CONSTRAINT IF EXISTS business_signals_status_check;
ALTER TABLE public.business_signals
  ADD CONSTRAINT business_signals_status_check
  CHECK (status IN ('open', 'resolved', 'dismissed', 'expired'));

ALTER TABLE public.financial_tasks
  ADD COLUMN IF NOT EXISTS assigned_user_id BIGINT
    REFERENCES public.users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS assignment_role TEXT NOT NULL DEFAULT 'owner',
  ADD COLUMN IF NOT EXISTS metadata JSONB NOT NULL DEFAULT '{}'::jsonb;

ALTER TABLE public.financial_tasks
  DROP CONSTRAINT IF EXISTS financial_tasks_assignment_role_check;
ALTER TABLE public.financial_tasks
  ADD CONSTRAINT financial_tasks_assignment_role_check
  CHECK (assignment_role IN ('owner', 'cpa', 'booksmart'));

CREATE TABLE IF NOT EXISTS public.financial_task_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL
    REFERENCES public.organizations(id) ON DELETE CASCADE,
  task_id BIGINT NOT NULL
    REFERENCES public.financial_tasks(id) ON DELETE CASCADE,
  actor_user_id BIGINT
    REFERENCES public.users(id) ON DELETE SET NULL,
  event_type TEXT NOT NULL
    CHECK (event_type IN ('created', 'started', 'waiting', 'completed', 'dismissed', 'reopened', 'updated')),
  from_status TEXT,
  to_status TEXT,
  note TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS business_signals_expiry_idx
  ON public.business_signals (organization_id, expires_at)
  WHERE status = 'open';

CREATE INDEX IF NOT EXISTS financial_task_events_task_idx
  ON public.financial_task_events (task_id, created_at DESC);

ALTER TABLE public.financial_task_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.financial_task_events FROM anon, authenticated;

COMMIT;
