create table if not exists public.financial_summary_rollout_events (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  surface text not null check (surface in ('home', 'reports')),
  mode text not null check (mode in ('canonical', 'fallback')),
  response_ms integer check (response_ms is null or response_ms between 0 and 300000),
  failure_reason text,
  calculation_version text not null,
  created_at timestamptz not null default now()
);

create index if not exists financial_summary_rollout_events_recent_idx
  on public.financial_summary_rollout_events (created_at desc);
create index if not exists financial_summary_rollout_events_org_surface_idx
  on public.financial_summary_rollout_events (organization_id, surface, created_at desc);

alter table public.financial_summary_rollout_events enable row level security;
revoke all on public.financial_summary_rollout_events from anon, authenticated;

comment on table public.financial_summary_rollout_events is
  'Read-only rollout diagnostics written by the API. Contains no transaction values or financial amounts.';
