CREATE TABLE IF NOT EXISTS public.quickbooks_connections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL UNIQUE REFERENCES public.organizations(id) ON DELETE CASCADE,
  realm_id TEXT NOT NULL,
  access_token_encrypted TEXT,
  refresh_token_encrypted TEXT,
  access_token_expires_at TIMESTAMPTZ,
  refresh_token_expires_at TIMESTAMPTZ,
  company_name TEXT,
  country TEXT,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disconnected', 'error')),
  verified_at TIMESTAMPTZ,
  connected_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  disconnected_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.quickbooks_connections ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.quickbooks_connections FROM anon, authenticated;

CREATE INDEX IF NOT EXISTS quickbooks_connections_realm_id_idx
  ON public.quickbooks_connections(realm_id);

CREATE TABLE IF NOT EXISTS public.quickbooks_oauth_states (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  state_hash TEXT NOT NULL UNIQUE,
  organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  auth_user_id UUID NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.quickbooks_oauth_states ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.quickbooks_oauth_states FROM anon, authenticated;
CREATE INDEX IF NOT EXISTS quickbooks_oauth_states_expires_at_idx
  ON public.quickbooks_oauth_states(expires_at);
