-- Targeted Gmail financial metadata and provenance only. This table is not an
-- accounting ledger and no row has accounting effect without a separately
-- approved canonical transaction.
BEGIN;

CREATE TABLE IF NOT EXISTS public.contractor_gmail_financial_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  gmail_message_id TEXT NOT NULL,
  gmail_thread_id TEXT,
  sender TEXT,
  subject TEXT,
  message_date TIMESTAMPTZ,
  attachment_names JSONB NOT NULL DEFAULT '[]'::jsonb,
  detected_document_type TEXT NOT NULL CHECK (detected_document_type IN (
    'receipt','vendor_invoice','customer_invoice','payment_notice','purchase_order',
    'change_order','insurance_notice','loan_notice','tax_notice','payroll_notice',
    'statement','unknown'
  )),
  extracted_reference_numbers JSONB NOT NULL DEFAULT '[]'::jsonb,
  linked_records JSONB NOT NULL DEFAULT '[]'::jsonb,
  confidence TEXT NOT NULL CHECK (confidence IN ('high','medium','low')),
  matched_signals JSONB NOT NULL DEFAULT '[]'::jsonb,
  requires_content_fetch BOOLEAN NOT NULL DEFAULT false,
  status TEXT NOT NULL DEFAULT 'detected' CHECK (status IN ('detected','linked','dismissed')),
  classification_version TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (organization_id, gmail_message_id)
);

CREATE INDEX IF NOT EXISTS contractor_gmail_messages_org_date_idx
  ON public.contractor_gmail_financial_messages (organization_id, message_date DESC);

ALTER TABLE public.contractor_gmail_financial_messages ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.contractor_gmail_financial_messages FROM anon, authenticated;

COMMIT;
