-- Central, pseudonymous, append-only security event trail.
BEGIN;

CREATE TABLE IF NOT EXISTS public.security_audit_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_key TEXT NOT NULL UNIQUE CHECK (char_length(event_key) BETWEEN 32 AND 128),
  event_type TEXT NOT NULL CHECK (event_type IN (
    'session_signed_in','session_signed_out','data_export','account_deletion',
    'integration_connection','cpa_access_change','cpa_order_change',
    'admin_account_change','admin_role_change'
  )),
  outcome TEXT NOT NULL CHECK (outcome IN ('succeeded','failed','denied')),
  actor_fingerprint TEXT CHECK (actor_fingerprint IS NULL OR actor_fingerprint ~ '^[0-9a-f]{64}$'),
  organization_fingerprint TEXT CHECK (organization_fingerprint IS NULL OR organization_fingerprint ~ '^[0-9a-f]{64}$'),
  target_fingerprint TEXT CHECK (target_fingerprint IS NULL OR target_fingerprint ~ '^[0-9a-f]{64}$'),
  source TEXT NOT NULL CHECK (source IN ('web','api','system')),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(metadata) = 'object'),
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  retain_until TIMESTAMPTZ NOT NULL DEFAULT (now() + interval '2 years')
);

CREATE INDEX IF NOT EXISTS security_audit_events_occurred_idx ON public.security_audit_events(occurred_at DESC);
CREATE INDEX IF NOT EXISTS security_audit_events_actor_idx ON public.security_audit_events(actor_fingerprint, occurred_at DESC);
CREATE INDEX IF NOT EXISTS security_audit_events_org_idx ON public.security_audit_events(organization_fingerprint, occurred_at DESC);
CREATE INDEX IF NOT EXISTS security_audit_events_retention_idx ON public.security_audit_events(retain_until);

ALTER TABLE public.security_audit_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.security_audit_events FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, DELETE ON public.security_audit_events TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.security_audit_events_id_seq TO service_role;

CREATE OR REPLACE FUNCTION public.prevent_security_audit_mutation()
RETURNS trigger LANGUAGE plpgsql SET search_path = pg_catalog AS $$
BEGIN
  IF TG_OP = 'DELETE' AND current_setting('booksmart.audit_retention_purge', true) = 'on'
     AND OLD.retain_until <= now() THEN RETURN OLD; END IF;
  RAISE EXCEPTION 'Security audit events are append-only until retention expires';
END;
$$;
DROP TRIGGER IF EXISTS prevent_security_audit_update_or_delete ON public.security_audit_events;
CREATE TRIGGER prevent_security_audit_update_or_delete BEFORE UPDATE OR DELETE ON public.security_audit_events
FOR EACH ROW EXECUTE FUNCTION public.prevent_security_audit_mutation();

CREATE OR REPLACE FUNCTION public.purge_expired_security_audit_events()
RETURNS BIGINT LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog SET row_security = off AS $$
DECLARE removed BIGINT;
BEGIN
  PERFORM set_config('booksmart.audit_retention_purge', 'on', true);
  DELETE FROM public.security_audit_events WHERE retain_until <= now();
  GET DIAGNOSTICS removed = ROW_COUNT;
  RETURN removed;
END;
$$;
REVOKE ALL ON FUNCTION public.purge_expired_security_audit_events() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.purge_expired_security_audit_events() TO service_role;

COMMIT;
