-- Organization-scoped planning inputs for future cash, tax, and forecast features.
-- These records are configuration only and never modify accounting transactions.

BEGIN;

CREATE TABLE IF NOT EXISTS public.financial_planning_settings (
  organization_id BIGINT PRIMARY KEY REFERENCES public.organizations(id) ON DELETE CASCADE,
  payroll_amount NUMERIC CHECK (payroll_amount IS NULL OR payroll_amount >= 0),
  payroll_cadence TEXT CHECK (payroll_cadence IS NULL OR payroll_cadence IN ('weekly','biweekly','semimonthly','monthly')),
  next_payroll_date DATE,
  operating_buffer NUMERIC CHECK (operating_buffer IS NULL OR operating_buffer >= 0),
  tax_effective_rate NUMERIC CHECK (tax_effective_rate IS NULL OR (tax_effective_rate >= 0 AND tax_effective_rate <= 100)),
  projected_taxable_income NUMERIC CHECK (projected_taxable_income IS NULL OR projected_taxable_income >= 0),
  tax_amount_set_aside NUMERIC CHECK (tax_amount_set_aside IS NULL OR tax_amount_set_aside >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.financial_planning_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  item_type TEXT NOT NULL CHECK (item_type IN ('obligation','receivable','filing_schedule')),
  name TEXT NOT NULL CHECK (char_length(btrim(name)) BETWEEN 1 AND 160),
  amount NUMERIC CHECK (amount IS NULL OR amount >= 0),
  due_date DATE NOT NULL,
  recurrence TEXT NOT NULL DEFAULT 'none' CHECK (recurrence IN ('none','weekly','monthly','quarterly','yearly')),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','completed','cancelled')),
  notes TEXT CHECK (notes IS NULL OR char_length(notes) <= 1000),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS financial_planning_items_org_due_idx
  ON public.financial_planning_items (organization_id, item_type, status, due_date);

CREATE TABLE IF NOT EXISTS public.financial_planning_audit_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  actor_user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
  action TEXT NOT NULL CHECK (action IN ('settings_updated','item_created','item_updated','item_deleted')),
  item_id BIGINT,
  changed_fields JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS financial_planning_audit_org_created_idx
  ON public.financial_planning_audit_events (organization_id, created_at DESC);

ALTER TABLE public.financial_planning_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.financial_planning_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.financial_planning_audit_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.financial_planning_settings FROM anon, authenticated;
REVOKE ALL ON public.financial_planning_items FROM anon, authenticated;
REVOKE ALL ON public.financial_planning_audit_events FROM anon, authenticated;

COMMIT;
