-- Persistent owner-visible activity notifications.
-- Transaction triggers capture manual, Plaid, QuickBooks, and statement-import
-- movements regardless of which application path performed the write.

BEGIN;

CREATE TABLE IF NOT EXISTS public.account_activity_notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  amount NUMERIC,
  route TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  read_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS account_activity_notifications_org_created_idx
  ON public.account_activity_notifications (organization_id, created_at DESC);
CREATE INDEX IF NOT EXISTS account_activity_notifications_org_unread_idx
  ON public.account_activity_notifications (organization_id, created_at DESC)
  WHERE read_at IS NULL;

ALTER TABLE public.account_activity_notifications ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.account_activity_notifications FROM anon, authenticated;

CREATE OR REPLACE FUNCTION public.notify_transaction_activity()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  row_value public.transactions%ROWTYPE;
  action_label TEXT;
BEGIN
  row_value := CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
  action_label := CASE TG_OP WHEN 'INSERT' THEN 'added' WHEN 'UPDATE' THEN 'updated' ELSE 'deleted' END;

  INSERT INTO public.account_activity_notifications (
    organization_id, event_type, title, description, amount, route, metadata
  ) VALUES (
    row_value.org_id,
    'transaction_' || lower(TG_OP),
    'Transaction ' || action_label,
    COALESCE(NULLIF(row_value.title, ''), NULLIF(row_value.description, ''), 'Transaction') ||
      CASE WHEN row_value.pending THEN ' is pending.' ELSE ' is reflected in approved activity.' END,
    row_value.amount,
    '/user/money',
    jsonb_build_object('transaction_id', row_value.id, 'source',
      CASE WHEN row_value.plaid_transaction_id IS NOT NULL THEN 'plaid'
           WHEN row_value.quickbooks_external_id IS NOT NULL THEN 'quickbooks'
           ELSE 'booksmart' END)
  );
  RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END;
$$;

DROP TRIGGER IF EXISTS transactions_activity_notification ON public.transactions;
CREATE TRIGGER transactions_activity_notification
AFTER INSERT OR UPDATE OR DELETE ON public.transactions
FOR EACH ROW EXECUTE FUNCTION public.notify_transaction_activity();

CREATE OR REPLACE FUNCTION public.notify_financial_task_activity()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF TG_OP = 'UPDATE' AND NEW.status IS NOT DISTINCT FROM OLD.status THEN RETURN NEW; END IF;
  INSERT INTO public.account_activity_notifications (organization_id, event_type, title, description, route, metadata)
  VALUES (NEW.organization_id, 'task_' || lower(TG_OP),
    CASE WHEN TG_OP = 'INSERT' THEN 'New financial task' ELSE 'Task status changed' END,
    NEW.title || CASE WHEN TG_OP = 'UPDATE' THEN ' is now ' || replace(NEW.status, '_', ' ') || '.' ELSE '.' END,
    '/user/tasks', jsonb_build_object('task_id', NEW.id, 'status', NEW.status));
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS financial_tasks_activity_notification ON public.financial_tasks;
CREATE TRIGGER financial_tasks_activity_notification
AFTER INSERT OR UPDATE OF status ON public.financial_tasks
FOR EACH ROW EXECUTE FUNCTION public.notify_financial_task_activity();

CREATE OR REPLACE FUNCTION public.notify_job_cost_activity()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE row_value public.contractor_job_cost_assignments%ROWTYPE;
BEGIN
  row_value := CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
  INSERT INTO public.account_activity_notifications (organization_id, event_type, title, description, amount, route, metadata)
  VALUES (row_value.organization_id, 'job_cost_' || lower(TG_OP),
    CASE WHEN TG_OP = 'INSERT' THEN 'Job cost approved' ELSE 'Job cost assignment removed' END,
    CASE WHEN TG_OP = 'INSERT' THEN 'An approved expense was assigned to a Jobber job.' ELSE 'An expense was removed from its Jobber job assignment.' END,
    row_value.amount, '/user/tasks', jsonb_build_object('assignment_id', row_value.id, 'source', row_value.source_provider));
  RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END;
$$;

DROP TRIGGER IF EXISTS contractor_job_cost_activity_notification ON public.contractor_job_cost_assignments;
CREATE TRIGGER contractor_job_cost_activity_notification
AFTER INSERT OR DELETE ON public.contractor_job_cost_assignments
FOR EACH ROW EXECUTE FUNCTION public.notify_job_cost_activity();

COMMIT;
