BEGIN;

CREATE TABLE IF NOT EXISTS public.jobber_expense_write_audit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  assignment_id BIGINT NOT NULL REFERENCES public.contractor_job_cost_assignments(id) ON DELETE RESTRICT,
  requested_by BIGINT NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
  status TEXT NOT NULL CHECK (status IN ('pending', 'succeeded', 'failed')),
  external_expense_id TEXT,
  request_payload JSONB NOT NULL,
  response_payload JSONB,
  error_message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ,
  UNIQUE (organization_id, assignment_id)
);

ALTER TABLE public.jobber_expense_write_audit ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.jobber_expense_write_audit FROM anon, authenticated;
GRANT ALL ON public.jobber_expense_write_audit TO service_role;

COMMIT;
