-- Append-only security and synchronization history for the Jobber integration.
-- This table stores event metadata only. OAuth tokens and imported record content
-- must never be written here.

CREATE TABLE IF NOT EXISTS public.jobber_audit_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  connection_id BIGINT REFERENCES public.jobber_connections(id) ON DELETE SET NULL,
  actor_user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
  event_type TEXT NOT NULL CHECK (event_type IN (
    'connect_started',
    'connected',
    'reconnected',
    'sync_started',
    'sync_completed',
    'sync_failed',
    'authorization_expired',
    'disconnected'
  )),
  outcome TEXT NOT NULL CHECK (outcome IN ('started','succeeded','failed','attention_required')),
  error_category TEXT CHECK (error_category IN (
    'reauthorization_required',
    'temporarily_unavailable',
    'configuration_error',
    'provider_error',
    'local_error'
  )),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.jobber_audit_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.jobber_audit_events FROM anon, authenticated;

CREATE INDEX IF NOT EXISTS jobber_audit_events_org_created_idx
  ON public.jobber_audit_events(organization_id, created_at DESC);

CREATE INDEX IF NOT EXISTS jobber_audit_events_connection_created_idx
  ON public.jobber_audit_events(connection_id, created_at DESC);

CREATE OR REPLACE FUNCTION public.prevent_jobber_audit_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'Jobber audit events are append-only';
END;
$$;

DROP TRIGGER IF EXISTS prevent_jobber_audit_update_or_delete ON public.jobber_audit_events;
CREATE TRIGGER prevent_jobber_audit_update_or_delete
BEFORE UPDATE OR DELETE ON public.jobber_audit_events
FOR EACH ROW EXECUTE FUNCTION public.prevent_jobber_audit_mutation();

