export const BUSINESS_ENTITY_TYPES = [
  "C Corporation",
  "General Partnership",
  "Limited Partnership",
  "LLP",
  "Multi Member LLC",
  "Nonprofit",
  "Other",
  "S Corporation",
  "Single Member LLC",
  "Sole Proprietor",
];

export const BUSINESS_ESTABLISHED_YEARS = Array.from(
  { length: new Date().getFullYear() - 1799 },
  (_, index) => String(new Date().getFullYear() - index),
);

export const BUSINESS_INDUSTRIES = [
  "Accounting & Finance",
  "Agriculture & Farming",
  "Automotive",
  "Beauty & Wellness",
  "Construction & Trades",
  "Consulting",
  "Education & Training",
  "Entertainment & Media",
  "Financial Services & Insurance",
  "Food & Beverage",
  "Government",
  "Healthcare & Medical",
  "Hospitality & Tourism",
  "Legal Services",
  "Manufacturing",
  "Marketing & Advertising",
  "Nonprofit",
  "Professional Services",
  "Real Estate",
  "Retail & E Commerce",
  "Self Employed/Gig Workers",
  "Sports & Recreation",
  "Technology & Startups",
  "Telecommunications",
  "Transportation & Logistics",
  "Utilities & Energy",
  "Wholesale & Distribution",
];

export const NAICS_BY_INDUSTRY: Record<string, string> = {
  "Agriculture & Farming": "11",
  "Construction & Trades": "23",
  "Education & Training": "61",
  Government: "92",
  "Healthcare & Medical": "62",
  Manufacturing: "31-33",
  Nonprofit: "813",
  "Real Estate": "531",
  "Retail & E Commerce": "44-45",
  "Transportation & Logistics": "48-49",
  "Utilities & Energy": "22",
  "Wholesale & Distribution": "42",
};
